# Generated by asn1c. Use 'make' to compile the converter example.
#
# If compiling manually without make, you must:
# 1. Use the -S flag when running asn1c to copy all required skeleton files
# 2. Compile with: -I. -lm flags
# 3. Include ALL .c files in the directory
#
# Recommended: just use 'make' instead of manual compilation
#
# PDU COLLECTION MODE: Multiple PDU types are available.
# The converter-example will default to the first PDU in pdu_collection.c
#
# To use a specific PDU type, add -DPDU=<TypeName> to CFLAGS below.
# Example: -DPDU=Certificate
#
# See pdu_collection.c for the list of available PDU types.

include Makefile.am.libasncodec

LIBS += -lm
CFLAGS += $(ASN_MODULE_CFLAGS) -DASN_PDU_COLLECTION -I.
ASN_LIBRARY ?= libasncodec.a
ASN_PROGRAM ?= converter-example
ASN_PROGRAM_SRCS ?= \
	converter-example.c\
	pdu_collection.c

all: $(ASN_PROGRAM)

$(ASN_PROGRAM): $(ASN_LIBRARY) $(ASN_PROGRAM_SRCS:.c=.o)
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $(ASN_PROGRAM) $(ASN_PROGRAM_SRCS:.c=.o) $(LDFLAGS) $(ASN_LIBRARY) $(LIBS)

$(ASN_LIBRARY): $(ASN_MODULE_SRCS:.c=.o)
	$(AR) rcs $@ $(ASN_MODULE_SRCS:.c=.o)

%.o: %.c
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f $(ASN_PROGRAM) $(ASN_LIBRARY)
	rm -f $(ASN_MODULE_SRCS:.c=.o) $(ASN_PROGRAM_SRCS:.c=.o)

regen: regenerate-from-asn1-source

regenerate-from-asn1-source:
	/home/runner/work/asn1c/asn1c/asn1c/asn1c -fcompound-names Module1.asn1 Module2.asn1

