/*
 * Generated by asn1c-44932e3-2026-01-13 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "Module1"
 * 	found in "Module1.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DL_CCCH_MessageType_H_
#define	_DL_CCCH_MessageType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRCSetup.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DL_CCCH_MessageType_PR {
	DL_CCCH_MessageType_PR_NOTHING,	/* No components present */
	DL_CCCH_MessageType_PR_c1
} DL_CCCH_MessageType_PR;
typedef enum DL_CCCH_MessageType__c1_PR {
	DL_CCCH_MessageType__c1_PR_NOTHING,	/* No components present */
	DL_CCCH_MessageType__c1_PR_rrcSetup,
	DL_CCCH_MessageType__c1_PR_messageClassExtension
} DL_CCCH_MessageType__c1_PR;

/* DL-CCCH-MessageType */
typedef struct DL_CCCH_MessageType {
	DL_CCCH_MessageType_PR present;
	union DL_CCCH_MessageType_u {
		struct DL_CCCH_MessageType__c1 {
			DL_CCCH_MessageType__c1_PR present;
			union DL_CCCH_MessageType__c1_u {
				RRCSetup_t	 rrcSetup;
				struct DL_CCCH_MessageType__c1__messageClassExtension {
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} messageClassExtension;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} c1;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_CCCH_MessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DL_CCCH_MessageType;

#ifdef __cplusplus
}
#endif

#endif	/* _DL_CCCH_MessageType_H_ */
#include <asn_internal.h>
