/*
 * Generated by asn1c-44932e3-2026-01-13 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "Module2"
 * 	found in "Module2.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DL_DCCH_MessageType_H_
#define	_DL_DCCH_MessageType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRCReconfiguration.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DL_DCCH_MessageType_PR {
	DL_DCCH_MessageType_PR_NOTHING,	/* No components present */
	DL_DCCH_MessageType_PR_c1
} DL_DCCH_MessageType_PR;
typedef enum DL_DCCH_MessageType__c1_PR {
	DL_DCCH_MessageType__c1_PR_NOTHING,	/* No components present */
	DL_DCCH_MessageType__c1_PR_rrcReconfiguration,
	DL_DCCH_MessageType__c1_PR_messageClassExtension
} DL_DCCH_MessageType__c1_PR;

/* DL-DCCH-MessageType */
typedef struct DL_DCCH_MessageType {
	DL_DCCH_MessageType_PR present;
	union DL_DCCH_MessageType_u {
		struct DL_DCCH_MessageType__c1 {
			DL_DCCH_MessageType__c1_PR present;
			union DL_DCCH_MessageType__c1_u {
				RRCReconfiguration_t	 rrcReconfiguration;
				struct DL_DCCH_MessageType__c1__messageClassExtension {
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} messageClassExtension;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} c1;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_DCCH_MessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DL_DCCH_MessageType;

#ifdef __cplusplus
}
#endif

#endif	/* _DL_DCCH_MessageType_H_ */
#include <asn_internal.h>
