/*
 * Generated by asn1c-44932e3-2026-01-13 (https://github.com/mouse07410/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_DL_CCCH_MessageType;
extern struct asn_TYPE_descriptor_s asn_DEF_DL_DCCH_MessageType;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module Module1 in Module1.asn1 */
	&asn_DEF_DL_CCCH_MessageType,	
	/* From module Module2 in Module2.asn1 */
	&asn_DEF_DL_DCCH_MessageType,	
	/* From module ASN1C-UsefulInformationObjectClasses in /home/runner/work/asn1c/asn1c/asn1c/../skeletons/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

