/*
 * Generated by asn1c-44932e3-2026-01-13 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "Module2"
 * 	found in "Module2.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RRCReconfiguration_H_
#define	_RRCReconfiguration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCReconfiguration__criticalExtensions_PR {
	RRCReconfiguration__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCReconfiguration__criticalExtensions_PR_rrcReconfiguration,
	RRCReconfiguration__criticalExtensions_PR_criticalExtensionsFuture
} RRCReconfiguration__criticalExtensions_PR;

/* RRCReconfiguration */
typedef struct RRCReconfiguration {
	struct RRCReconfiguration__criticalExtensions {
		RRCReconfiguration__criticalExtensions_PR present;
		union RRCReconfiguration__criticalExtensions_u {
			struct RRCReconfiguration__criticalExtensions__rrcReconfiguration {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} rrcReconfiguration;
			struct RRCReconfiguration__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCReconfiguration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCReconfiguration;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCReconfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCReconfiguration_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCReconfiguration_H_ */
#include <asn_internal.h>
