/*
 * Generated by asn1c-44932e3-2026-01-13 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "Module1"
 * 	found in "Module1.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RRCSetup_H_
#define	_RRCSetup_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCSetup__criticalExtensions_PR {
	RRCSetup__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCSetup__criticalExtensions_PR_rrcSetup,
	RRCSetup__criticalExtensions_PR_criticalExtensionsFuture
} RRCSetup__criticalExtensions_PR;

/* RRCSetup */
typedef struct RRCSetup {
	struct RRCSetup__criticalExtensions {
		RRCSetup__criticalExtensions_PR present;
		union RRCSetup__criticalExtensions_u {
			struct RRCSetup__criticalExtensions__rrcSetup {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} rrcSetup;
			struct RRCSetup__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCSetup_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCSetup;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCSetup_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCSetup_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCSetup_H_ */
#include <asn_internal.h>
