/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST3"
 * 	found in "/tmp/test3.asn"
 */

#ifndef	_RaAcaCertRequest_H_
#define	_RaAcaCertRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RaAcaCertRequest */
typedef OCTET_STRING_t	 RaAcaCertRequest_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RaAcaCertRequest_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RaAcaCertRequest;
asn_struct_free_f RaAcaCertRequest_free;
asn_struct_print_f RaAcaCertRequest_print;
asn_constr_check_f RaAcaCertRequest_constraint;
ber_type_decoder_f RaAcaCertRequest_decode_ber;
der_type_encoder_f RaAcaCertRequest_encode_der;
xer_type_decoder_f RaAcaCertRequest_decode_xer;
xer_type_encoder_f RaAcaCertRequest_encode_xer;
jer_type_encoder_f RaAcaCertRequest_encode_jer;
oer_type_decoder_f RaAcaCertRequest_decode_oer;
oer_type_encoder_f RaAcaCertRequest_encode_oer;
per_type_decoder_f RaAcaCertRequest_decode_uper;
per_type_encoder_f RaAcaCertRequest_encode_uper;
per_type_decoder_f RaAcaCertRequest_decode_aper;
per_type_encoder_f RaAcaCertRequest_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RaAcaCertRequest_H_ */
#include <asn_internal.h>
