/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST3"
 * 	found in "/tmp/test3.asn"
 */

#ifndef	_ScmsPdu_Scoped_H_
#define	_ScmsPdu_Scoped_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ScmsPdu.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ScmsPdu-Scoped */
typedef ScmsPdu_t	 ScmsPdu_Scoped_24P0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScmsPdu_Scoped_24P0;
asn_struct_free_f ScmsPdu_Scoped_24P0_free;
asn_struct_print_f ScmsPdu_Scoped_24P0_print;
asn_constr_check_f ScmsPdu_Scoped_24P0_constraint;
ber_type_decoder_f ScmsPdu_Scoped_24P0_decode_ber;
der_type_encoder_f ScmsPdu_Scoped_24P0_encode_der;
xer_type_decoder_f ScmsPdu_Scoped_24P0_decode_xer;
xer_type_encoder_f ScmsPdu_Scoped_24P0_encode_xer;
jer_type_encoder_f ScmsPdu_Scoped_24P0_encode_jer;
oer_type_decoder_f ScmsPdu_Scoped_24P0_decode_oer;
oer_type_encoder_f ScmsPdu_Scoped_24P0_encode_oer;
per_type_decoder_f ScmsPdu_Scoped_24P0_decode_uper;
per_type_encoder_f ScmsPdu_Scoped_24P0_encode_uper;
per_type_decoder_f ScmsPdu_Scoped_24P0_decode_aper;
per_type_encoder_f ScmsPdu_Scoped_24P0_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ScmsPdu_Scoped_H_ */
#include <asn_internal.h>
