/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST3"
 * 	found in "/tmp/test3.asn"
 */

#ifndef	_ScmsPdu_H_
#define	_ScmsPdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint8.h"
#include "AcaRaInterfacePdu.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum content_PR {
	content_PR_NOTHING,	/* No components present */
	content_PR_aca_ra
	/* Extensions may appear below */
	
} content_PR;

/* ScmsPdu */
typedef struct ScmsPdu {
	Uint8_t	 version;
	struct content {
		content_PR present;
		union ScmsPdu__content_u {
			AcaRaInterfacePdu_t	 aca_ra;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} content;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScmsPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScmsPdu;
extern asn_SEQUENCE_specifics_t asn_SPC_ScmsPdu_specs_1;
extern asn_TYPE_member_t asn_MBR_ScmsPdu_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ScmsPdu_H_ */
#include <asn_internal.h>
