/*
 * Generated by asn1c-64039e0-2026-05-03 (https://github.com/mouse07410/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_S1AP_InitiatingMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_S1AP_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module TestModule in test.asn */
	&asn_DEF_S1AP_InitiatingMessage,	
	/* From module ASN1C-UsefulInformationObjectClasses in .././skeletons/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_S1AP_EXTERNAL,	
	0
};

