/*
 * Generated by asn1c-64039e0-2026-05-03 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "TestModule"
 * 	found in "test.asn"
 * 	`asn1c -S .././skeletons -flink-skeletons -fprefix=S1AP_ -D S1AP_`
 */

#include "S1AP_InitiatingMessage.h"

#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_S1AP_value __attribute__((weak, alias("asn_DEF_S1AP_value_2")));
#else
static asn_TYPE_descriptor_t asn_DEF_S1AP_value_2;
static asn_TYPE_descriptor_t asn_DEF_S1AP_value;
__attribute__((constructor)) static void asn_DEF_S1AP_value_2_alias_init(void) {
	asn_DEF_S1AP_value = asn_DEF_S1AP_value_2;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
static asn_TYPE_member_t asn_MBR_S1AP_InitiatingMessage__value_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_value, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_value, payload),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"payload"
		},
};
static const ber_tlv_tag_t asn_DEF_S1AP_value_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_S1AP_value_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* payload */
};
static asn_SEQUENCE_specifics_t asn_SPC_S1AP_value_specs_2 = {
	sizeof(struct S1AP_value),
	offsetof(struct S1AP_value, _asn_ctx),
	asn_MAP_S1AP_value_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_S1AP_value_2 = {
	"value",
	"value",
	&asn_OP_SEQUENCE,
	asn_DEF_S1AP_value_tags_2,
	sizeof(asn_DEF_S1AP_value_tags_2)
		/sizeof(asn_DEF_S1AP_value_tags_2[0]) - 1, /* 1 */
	asn_DEF_S1AP_value_tags_2,	/* Same as above */
	sizeof(asn_DEF_S1AP_value_tags_2)
		/sizeof(asn_DEF_S1AP_value_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_S1AP_InitiatingMessage__value_2,
	2,	/* Elements count */
	&asn_SPC_S1AP_value_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_S1AP_InitiatingMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_InitiatingMessage, value),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_S1AP_value_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_S1AP_InitiatingMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_S1AP_InitiatingMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* value */
};
static asn_SEQUENCE_specifics_t asn_SPC_S1AP_InitiatingMessage_specs_1 = {
	sizeof(struct S1AP_InitiatingMessage),
	offsetof(struct S1AP_InitiatingMessage, _asn_ctx),
	asn_MAP_S1AP_InitiatingMessage_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_S1AP_InitiatingMessage = {
	"InitiatingMessage",
	"InitiatingMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_S1AP_InitiatingMessage_tags_1,
	sizeof(asn_DEF_S1AP_InitiatingMessage_tags_1)
		/sizeof(asn_DEF_S1AP_InitiatingMessage_tags_1[0]), /* 1 */
	asn_DEF_S1AP_InitiatingMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_S1AP_InitiatingMessage_tags_1)
		/sizeof(asn_DEF_S1AP_InitiatingMessage_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_S1AP_InitiatingMessage_1,
	1,	/* Elements count */
	&asn_SPC_S1AP_InitiatingMessage_specs_1	/* Additional specs */
};

