/*
 * Generated by asn1c-64039e0-2026-05-03 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "TestModule"
 * 	found in "test.asn"
 * 	`asn1c -S .././skeletons -flink-skeletons -fprefix=S1AP_ -D S1AP_`
 */

#ifndef	_S1AP_InitiatingMessage_H_
#define	_S1AP_InitiatingMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* S1AP_InitiatingMessage */
typedef struct S1AP_InitiatingMessage {
	struct S1AP_value {
		long	 id;
		OCTET_STRING_t	 payload;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_InitiatingMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_InitiatingMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_InitiatingMessage_H_ */
#include <asn_internal.h>
