#ifndef ASN1_COMPILER_LANDUAGE_PY_H
#define ASN1_COMPILER_LANDUAGE_PY_H

#include "asn1c_internal.h"
#include "asn1c_Py.h"
#include "asn1c_out.h"
#include "asn1c_misc.h"
#include "asn1c_naming.h"
#include "asn1c_py_out.h"

#include <asn1parser.h>
#include <asn1print.h>
#include <asn1fix_crange.h> /* constraint groker from libasn1fix */
#include <asn1fix_export.h> /* other exportables from libasn1fix */

#define MKID(expr) (asn1c_make_identifier(AMI_USE_PREFIX, expr, 0))
#define MKID_safe(expr) (asn1c_make_identifier(AMI_CHECK_RESERVED, expr, 0))

#define TYPE_IS_SIGNED(arg, expr) \
    (asn1c_type_fits_long(arg, expr) != FL_FITS_UNSIGN)
#define TYPE_IS_UNION(expr) (expr) && (expr->expr_type == ASN_CONSTR_CHOICE)
#define TYPE_IS_FLOAT(expr) (asn1c_expr_is_float32(expr))
#define TYPE_IS_SEQ_LIKE(expr_type) \
    ((expr_type) == ASN_CONSTR_SEQUENCE || (expr_type) == ASN_CONSTR_SET)
#define TYPE_IS_SET(expr) (expr) && (expr->expr_type == ASN_CONSTR_SET)

#define ASN1C_MAX_INT_WIDTH 20

enum {
    PYTNF_NONE = 0x00,
    PYTNF_CONSTR = 0x01,
    PYTNF_CLASS = 0x02,
};

/**
 * @brief Builds a path string that references an anonymous type definition in C
 * (as generated by the ASN.1 compiler), like:
 *
 *      asn_DEF_<parent>.elements[<index>].type
 *
 * Or, for nested anonymous types:
 *
 *      asn_DEF_<grandparent>.elements[<parent_index>].type->elements[<index>].type
 */
static char *py_get_anonymous_type_def(arg_t *arg, asn1p_expr_t *expr,
                                       const char *name);
static int asn1c_expr_is_float32(asn1p_expr_t *expr);
static char *py_type_name(arg_t *arg, asn1p_expr_t *expr, int flags);
static char *get_py_class_name(arg_t *arg, asn1p_expr_t *expr);
static char *py_parent_type_name(arg_t *arg, asn1p_expr_t *expr);
static size_t asn1c_get_member_index(arg_t *arg, asn1p_expr_t *expr,
                                     const char *name);
static int expr_elements_count(arg_t *arg, asn1p_expr_t *expr);

/* global functions */
int
asn1c_lang_Py_type_SEQUENCE(arg_t *arg) {
    asn1p_expr_t *expr;
    asn1p_expr_t *v;

    char *type_name;
    char *constr_struct_name;
    char *py_class_name;
    char *parent_type_name;
    char *inner_parent_name;
    char *constr_path;
    char *inner_parent_struct_name;

    int saved_target;
    int indirect;
    int optional;
    int parent_is_choice;
    int parent_is_set;

    expr = arg->expr;
    v = NULL;
    type_name = py_type_name(arg, expr, PYTNF_CONSTR);
    constr_struct_name = strdup(MKID(arg->expr));
    py_class_name = get_py_class_name(arg, expr);
    parent_type_name = py_parent_type_name(arg, expr);
    inner_parent_name = NULL;
    constr_path = NULL;
    inner_parent_struct_name = NULL;
    saved_target = arg->target->target;
    optional = expr->marker.flags & EM_OPTIONAL;
    indirect = (optional) || (expr->marker.flags & EM_INDIRECT);
    parent_is_choice = TYPE_IS_UNION(expr->parent_expr);
    parent_is_set = TYPE_IS_SET(expr->parent_expr);


    PY_GEN_DEFAULT_INCLUDE();
    /* type def */
    REDIR(OT_PY_TYPE_DECLS);
    if(arg->embed) {
        OUT("PyCompat_DEF_ANON_STRUCT(%s, %s);\n", type_name,
            constr_struct_name);
        OUT("PyCompat_DEF_TYPE(%s);\n", type_name);
        // this is debateable:
        // OUT("typedef struct %s %s_t;\n", constr_struct_name,
        //     constr_struct_name);
        constr_path = py_get_anonymous_type_def(arg, expr, constr_struct_name);
        assert(constr_path);

        if(arg->embed > 1) {
            inner_parent_name =
                py_type_name(arg, expr->parent_expr, PYTNF_CONSTR);
            inner_parent_struct_name = strdup(MKID(expr->parent_expr));
        }
    } else {
        PY_GEN_DEF_TYPE(type_name);
    }

    /* type converters */
    REDIR(OT_PY_TYPE_CONVERT);
    if(arg->embed) {
        OUT("int PyAsn%s_FromPython(PyObject *pObj, struct %s *pDst);\n",
            type_name, constr_struct_name);
        OUT("PyObject *PyAsn%s_ToPython(struct %s *pSrc, PyObject *parent);\n",
            type_name, constr_struct_name);
    } else {
        PY_GEN_ASNTYPE_FROMPY(type_name);
        PY_GEN_ASNTYPE_TOPY(type_name);
    }

    REDIR(OT_PY_IMPL_CODE);
    /* default methods */
    if(arg->embed) {
        OUT("PY_IMPL_CHECK_CONSTRAINTS(%s, %s);\n", type_name, constr_path);
        OUT("PY_IMPL_ENCODE(%s, %s);\n", type_name, constr_path);
        OUT("PY_IMPL_DECODE(%s, %s);\n", type_name, constr_path);
        /*
         * DEALLOC is a bit special as it requires us to dereference the
         * type_DEF pointer.
         */
        OUT("PY_IMPL_DEALLOC(%s, *(%s));\n", type_name, constr_path);
        OUT("PY_IMPL_SEQ_TOPY(%s, %s);\n", type_name, constr_path);
    } else {
        PY_GEN_TYPE_DEALLOC(type_name);
        PY_GEN_TYPE_CHECK_CONSTRAINTS(type_name);
        PY_GEN_TYPE_ENCODE(type_name);
        PY_GEN_TYPE_DECODE(type_name);
        OUT("PY_IMPL_SEQ_GENERIC_TOPY(%s);\n", type_name);
    }
    PY_GEN_TYPE_PARSERS(type_name);

    /* next methods are shared */
    PY_GEN_TYPE_NEW(type_name);
    PY_GEN_TYPE_REPR(type_name);
    PY_GEN_TYPE_IS_VALID(type_name);
    OUT("PY_IMPL_SEQ_FROMPY(%s,\n", type_name);
    INDENT(+1);
    TQ_FOR(v, &(expr->members), next) {
        if(v->expr_type == A1TC_EXTENSIBLE) continue;
        OUT("PY_IMPL_SEQ_INIT_ATTR(%s, %s);\n", type_name, MKID_safe(v));
    }
    INDENT(-1);
    OUT(");\n");
    OUT("PY_IMPL_SEQ_INIT(%s);\n", type_name);
    if(arg->embed) {
        /* make sure the parent class can use this anonymous inner type */
        int deep_embed = arg->embed > 1;
        OUT("PY_IMPL_SEQ_ANON_ATTR_FROMPY(%s, %s, %s%s%s, %s);\n",
            deep_embed ? inner_parent_name : parent_type_name,
            constr_struct_name, (indirect ? "" : "&"),
            (parent_is_choice ? "src->choice." : "src->"), constr_struct_name,
            type_name);
        OUT("PY_IMPL_SEQ_ANON_ATTR_TOPY(%s, %s, %s%s%s, %s);\n",
            deep_embed ? inner_parent_name : parent_type_name,
            constr_struct_name, (indirect ? "" : "&"),
            (parent_is_choice ? "src->choice." : "src->"), constr_struct_name,
            type_name);

        if(parent_is_choice) {
            OUT("PY_IMPL_CHOICE_GENERIC_SETATTR(%s, %s, %s, *%s);\n",
                deep_embed ? inner_parent_name : parent_type_name,
                deep_embed ? inner_parent_struct_name : parent_type_name,
                constr_struct_name, constr_path);
            OUT("PY_IMPL_CHOICE_GETATTR(%s, %s, %s);\n",
                deep_embed ? inner_parent_name : parent_type_name,
                deep_embed ? inner_parent_struct_name : parent_type_name,
                constr_struct_name);
        } else {
            if(parent_is_set) {
                OUT("PY_IMPL_SET_INNER%s_SETATTR(%s, %s, %s, %s, %s);\n",
                    optional ? "_OPT" : "",
                    deep_embed ? inner_parent_name : parent_type_name,
                    deep_embed ? inner_parent_struct_name : parent_type_name,
                    constr_struct_name, constr_struct_name, type_name);
                OUT("PY_IMPL_SET_INNER_GETATTR(%s, %s, %s, "
                    "%sself->ob_value->%s, "
                    "%s);\n",
                    deep_embed ? inner_parent_name : parent_type_name,
                    deep_embed ? inner_parent_struct_name : parent_type_name,
                    constr_struct_name, (indirect ? "" : "&"),
                    constr_struct_name, type_name);
            } else {
                OUT("PY_IMPL_SEQ_INNER%s_SETATTR(%s, %s, %s, %s);\n",
                    optional ? "_OPT" : "",
                    deep_embed ? inner_parent_name : parent_type_name,
                    constr_struct_name, constr_struct_name, type_name);
                OUT("PY_IMPL_SEQ_INNER_GETATTR(%s, %s, %sself->ob_value->%s, "
                    "%s);\n",
                    deep_embed ? inner_parent_name : parent_type_name,
                    constr_struct_name, (indirect ? "" : "&"),
                    constr_struct_name, type_name);
            }
        }
    }

    /* methods for SEQ objects will be the same */
    REDIR(OT_PY_IMPL_METHODS);
    PY_GEN_TYPE_METHODS_BEGIN(type_name);
    PY_GEN_TYPE_DEFAULT_METHODS(type_name);
    PY_GEN_TYPE_METHODS_END();

    /* members according to the ASN.1 type */
    REDIR(OT_PY_IMPL_ATTRS);
    PY_GEN_TYPE_ATTRS_BEGIN(type_name);
    TQ_FOR(v, &(expr->members), next) {
        if(v->expr_type == A1TC_EXTENSIBLE) continue;
        PY_GEN_TYPE_ATTRSTR(type_name, MKID_safe(v));
    }
    PY_GEN_TYPE_ATTRS_END();

    /* type spec */
    REDIR(OT_PY_IMPL_CLASS);
    PY_GEN_CLASS_BEGIN_INTERNAL(arg->pymodule_qualname, type_name,
                                py_class_name);
    if(arg->embed) {
        PY_GEN_CLASS_DOC(
            "ASN.1 anonymous type %s_TYPE part of %s", constr_struct_name,
            arg->embed > 1 ? MKID(expr->parent_expr) : parent_type_name);
    } else {
        PY_GEN_CLASS_DOC("ASN.1 %s type", py_class_name);
    }
    PY_GEN_CLASS_END();

    /* mod init */
    REDIR(OT_PY_IMPL_CODE_MOD_SETUP);
    INDENTED(PY_GEN_MOD_SETUP_SINGLE(type_name));
    REDIR(OT_PY_IMPL_CODE_MOD_INIT);
    if(arg->embed == 1) {
        INDENTED(OUT("PY_IMPL_MOD_ASSIGN_OBJECT(%s, %s_TYPE, &PyAsn%s_Type);\n",
                     parent_type_name, constr_struct_name, type_name));
    } else if(arg->embed == 0) {
        INDENTED(PY_GEN_MOD_INIT_SINGLE(type_name));
    } else {
        /* this could be used to set the new type into another anonymous SEQ */
        INDENTED(OUT("PY_IMPL_MOD_ASSIGN_OBJECT(%s, %s_TYPE, &PyAsn%s_Type);\n",
                     inner_parent_name, constr_struct_name, type_name));
    }

    ASN_XFREE(type_name);
    ASN_XFREE(constr_struct_name);
    ASN_XFREE(py_class_name);
    ASN_XFREE(parent_type_name);
    ASN_XFREE(inner_parent_name);
    ASN_XFREE(inner_parent_struct_name);
    REDIR(saved_target);
    return 0;
}

int
asn1c_lang_Py_type_CHOICE(arg_t *arg) {
    asn1p_expr_t *expr = arg->expr;
    asn1p_expr_t *v;

    char *type_name;
    char *constr_struct_name;
    char *py_class_name;
    char *parent_type_name;
    char *inner_parent_name;
    char *constr_path;
    char *inner_parent_struct_name;

    int saved_target;
    int parent_is_choice;
    int deep_embed;
    int indirect;
    int optional;
    int parent_is_set;
    size_t presence_value = 0;

    type_name = py_type_name(arg, expr, PYTNF_CONSTR);
    constr_struct_name = strdup(MKID(expr));
    py_class_name = get_py_class_name(arg, expr);
    parent_type_name = py_parent_type_name(arg, expr);
    inner_parent_name = NULL;
    inner_parent_struct_name = NULL;
    constr_path = NULL;
    saved_target = arg->target->target;
    parent_is_choice = TYPE_IS_UNION(expr->parent_expr);
    deep_embed = arg->embed > 1;
    optional = expr->marker.flags & EM_OPTIONAL;
    indirect = (optional) || (expr->marker.flags & EM_INDIRECT);
    parent_is_set = TYPE_IS_SET(expr->parent_expr);

    PY_GEN_DEFAULT_INCLUDE();
    REDIR(OT_PY_TYPE_DECLS);
    if(arg->embed) {
        OUT("PyCompat_DEF_ANON_STRUCT(%s, %s);\n", type_name,
            constr_struct_name);
        OUT("PyCompat_DEF_TYPE(%s);\n", type_name);
        constr_path = py_get_anonymous_type_def(arg, expr, constr_struct_name);
        assert(constr_path);

        if(arg->embed > 1) {
            inner_parent_name =
                py_type_name(arg, expr->parent_expr, PYTNF_CONSTR);
            inner_parent_struct_name = strdup(MKID(expr->parent_expr));
        }
    } else {
        PY_GEN_DEF_TYPE(type_name);
    }

    /* additionally, introduce the presence enum */
    OUT("PyCompat_DEF_ENUM(%s_PRESENT);\n", type_name);

    REDIR(OT_PY_TYPE_CONVERT);
    PY_GEN_ASNTYPE_FROMPY(type_name);
    PY_GEN_ASNTYPE_TOPY(type_name);

    REDIR(OT_PY_IMPL_CODE);
    /* default methods */

    if(arg->embed) {
        OUT("PY_IMPL_CHECK_CONSTRAINTS(%s, %s);\n", type_name, constr_path);
        OUT("PY_IMPL_ENCODE(%s, %s);\n", type_name, constr_path);
        OUT("PY_IMPL_DECODE(%s, %s);\n", type_name, constr_path);
        /*
         * DEALLOC is a bit special as it requires us to dereference the
         * type_DEF pointer.
         */
        OUT("PY_IMPL_DEALLOC(%s, *(%s));\n", type_name, constr_path);
        OUT("PY_IMPL_SEQ_TOPY(%s, %s);\n", type_name, constr_path);
        OUT("PY_IMPL_GENERIC_REPR(%s, %s);\n", type_name, constr_struct_name);
    } else {
        PY_GEN_TYPE_DEALLOC(type_name);
        PY_GEN_TYPE_CHECK_CONSTRAINTS(type_name);
        PY_GEN_TYPE_ENCODE(type_name);
        PY_GEN_TYPE_DECODE(type_name);
        PY_GEN_TYPE_REPR(type_name);
        OUT("PY_IMPL_SEQ_GENERIC_TOPY(%s);\n", type_name);
    }
    PY_GEN_TYPE_PARSERS(type_name);

    OUT("PyObject *PyAsnEnum%s_PRESENT_Type = NULL;\n", type_name);
    OUT("PY_IMPL_CHOICE_PRESENT_ATTR(%s);\n", type_name);

    PY_GEN_TYPE_NEW(type_name);

    PY_GEN_TYPE_IS_VALID(type_name);
    /* Conversion from a generic Python object for CHOICE */
    OUT("PY_IMPL_SEQ_FROMPY(%s,\n", type_name);
    INDENT(+1);
    TQ_FOR(v, &(expr->members), next) {
        if(v->expr_type == A1TC_EXTENSIBLE) continue;
        OUT("PY_IMPL_SEQ_INIT_ATTR(%s, %s);\n", type_name, MKID_safe(v));
    }
    INDENT(-1);
    OUT(");\n");

    /* init is just calling FromPython(...) */
    if(arg->embed) {
        OUT("PY_IMPL_CHOICE_INIT_GENERIC(%s, %s);\n", type_name,
            constr_struct_name);

        OUT("PY_IMPL_SEQ_ANON_ATTR_FROMPY(%s, %s, %s%s%s, %s);\n",
            deep_embed ? inner_parent_name : parent_type_name,
            constr_struct_name, (indirect ? "" : "&"),
            (parent_is_choice ? "src->choice." : "src->"), constr_struct_name,
            type_name);
        OUT("PY_IMPL_SEQ_ANON_ATTR_TOPY(%s, %s, %s%s%s, %s);\n",
            deep_embed ? inner_parent_name : parent_type_name,
            constr_struct_name, (indirect ? "" : "&"),
            (parent_is_choice ? "src->choice." : "src->"), constr_struct_name,
            type_name);

        if(parent_is_choice) {
            OUT("PY_IMPL_CHOICE_GENERIC_SETATTR(%s, %s, %s, *%s);\n",
                deep_embed ? inner_parent_name : parent_type_name,
                deep_embed ? inner_parent_struct_name : parent_type_name,
                constr_struct_name, constr_path);
            OUT("PY_IMPL_CHOICE_GETATTR(%s, %s, %s);\n",
                deep_embed ? inner_parent_name : parent_type_name,
                deep_embed ? inner_parent_struct_name : parent_type_name,
                constr_struct_name);
        } else {
            if(parent_is_set) {
                OUT("PY_IMPL_SET_INNER%s_SETATTR(%s, %s, %s, %s, %s);\n",
                    optional ? "_OPT" : "",
                    deep_embed ? inner_parent_name : parent_type_name,
                    deep_embed ? inner_parent_struct_name : parent_type_name,
                    constr_struct_name, constr_struct_name, type_name);
                OUT("PY_IMPL_SET_INNER_GETATTR(%s, %s, %s, "
                    "%sself->ob_value->%s, "
                    "%s);\n",
                    deep_embed ? inner_parent_name : parent_type_name,
                    deep_embed ? inner_parent_struct_name : parent_type_name,
                    constr_struct_name, (indirect ? "" : "&"),
                    constr_struct_name, type_name);
            } else {
                OUT("PY_IMPL_SEQ_INNER%s_SETATTR(%s, %s, %s, %s);\n",
                    optional ? "_OPT" : "",
                    deep_embed ? inner_parent_name : parent_type_name,
                    constr_struct_name, constr_struct_name, type_name);
                OUT("PY_IMPL_SEQ_INNER_GETATTR(%s, %s, %sself->ob_value->%s, "
                    "%s);\n",
                    deep_embed ? inner_parent_name : parent_type_name,
                    constr_struct_name, (indirect ? "" : "&"),
                    constr_struct_name, type_name);
            }
        }
    } else {
        OUT("PY_IMPL_CHOICE_INIT(%s);\n", type_name);
    }

    /* methods for CHOICE objects will be the same */
    REDIR(OT_PY_IMPL_METHODS);
    PY_GEN_TYPE_METHODS_BEGIN(type_name);
    PY_GEN_TYPE_DEFAULT_METHODS(type_name);
    PY_GEN_TYPE_METHODS_END();

    /* members according to the ASN.1 type */
    REDIR(OT_PY_IMPL_ATTRS);
    PY_GEN_TYPE_ATTRS_BEGIN(type_name);
    OUT("{\"present\",  (getter)PyAsn%s__get_present, NULL, NULL, "
        "NULL},\n",
        type_name);
    TQ_FOR(v, &(expr->members), next) {
        if(v->expr_type == A1TC_EXTENSIBLE) continue;
        PY_GEN_TYPE_ATTRSTR(type_name, MKID_safe(v));
    }
    PY_GEN_TYPE_ATTRS_END();

    /* type spec */
    REDIR(OT_PY_IMPL_CLASS);
    PY_GEN_CLASS_BEGIN_INTERNAL(arg->pymodule_qualname, type_name,
                                py_class_name);
    if(arg->embed) {
        PY_GEN_CLASS_DOC(
            "ASN.1 anonymous type %s_TYPE part of %s", constr_struct_name,
            arg->embed > 1 ? MKID(expr->parent_expr) : parent_type_name);
    } else {
        PY_GEN_CLASS_DOC("ASN.1 %s type", py_class_name);
    }
    PY_GEN_CLASS_END();

    /* module init */
    REDIR(OT_PY_IMPL_CODE_MOD_CLEAR);
    INDENTED(OUT("Py_CLEAR(PyAsnEnum%s_PRESENT_Type);\n", type_name));

    REDIR(OT_PY_IMPL_CODE_MOD_INIT);
    INDENT(+1);
    OUT("PY_IMPL_NEW_ENUM(%s.PRESENT, PyAsnEnum%s_PRESENT_Type, -1, \n",
        py_class_name, type_name);
    INDENT(+1);
    OUT("PY_IMPL_ENUM_VALUE(PR_NOTHING, %s_PR_NOTHING, %ld);\n",
        constr_struct_name, presence_value);
    presence_value++;
    TQ_FOR(v, &(expr->members), next) {
        if(v->expr_type == A1TC_EXTENSIBLE) {
            OUT("/* Extensions may appear below */\n");
            continue;
        }

        OUT("PY_IMPL_ENUM_VALUE(PR_%s, %s, %ld);\n", MKID_safe(v),
            c_presence_name(arg, v), presence_value);
        presence_value++;
    }
    INDENT(-1);
    OUT(");\n");
    OUT("PY_IMPL_ASSIGN_ENUM_DIRECT(%s, %s_PRESENT, PRESENT);\n", type_name,
        type_name);
    INDENT(-1);

    if(arg->embed == 1) {
        INDENTED(OUT("PY_IMPL_MOD_ASSIGN_OBJECT(%s, %s_TYPE, &PyAsn%s_Type);\n",
                     parent_type_name, constr_struct_name, type_name));
    } else if(arg->embed > 1) {
        INDENTED(OUT("PY_IMPL_MOD_ASSIGN_OBJECT(%s, %s_TYPE, &PyAsn%s_Type);\n",
                     inner_parent_name, constr_struct_name, type_name));
    }

    PY_GEN_MOD_BASIC(type_name);

    ASN_XFREE(type_name);
    ASN_XFREE(constr_struct_name);
    ASN_XFREE(py_class_name);
    ASN_XFREE(parent_type_name);
    ASN_XFREE(inner_parent_name);
    REDIR(saved_target);
    return 0;
}

int
asn1c_lang_Py_type_SIMPLE_TYPE(arg_t *arg) {
    asn1p_expr_t *expr;
    asn1p_expr_t *v;

    enum asn1p_expr_type parent_expr_type;
    size_t enum_member_name_len;

    const char *tmp_name;
    char *parent_type_name;
    char *parent_struct_name;
    char *ref_type_name;
    char *el_member_name;
    char *name;
    char *constr_enum_name;
    char *constr_parent_path;

    int saved_target;
    int el_count;
    int optional;
    int indirect;
    int is_signed;
    int is_bitstr;


    expr = arg->expr;
    saved_target = arg->target->target;
    parent_expr_type =
        expr->parent_expr ? expr->parent_expr->expr_type : ASN_EXPR_TYPE_MAX;
    el_count = expr_elements_count(arg, expr);
    optional = expr->marker.flags & EM_OPTIONAL;
    indirect = expr->marker.flags & EM_INDIRECT;
    is_signed = TYPE_IS_SIGNED(arg, expr);
    is_bitstr = arg->expr->expr_type == ASN_BASIC_BIT_STRING;
    parent_type_name = NULL;
    parent_struct_name = NULL;
    ref_type_name = NULL;
    el_member_name = NULL;
    constr_enum_name = NULL;
    constr_parent_path = NULL;

    if(expr->parent_expr) {
        parent_type_name = py_type_name(arg, expr->parent_expr, PYTNF_NONE);
        parent_struct_name = strdup(MKID(expr->parent_expr));
        if(arg->embed > 1) {
            constr_parent_path = py_get_anonymous_type_def(
                arg, expr->parent_expr, parent_struct_name);
        }
    }
    if(arg->embed) {
        name = strdup(asn1c_type_name(arg, arg->expr, TNF_CTYPE));
        el_member_name = strdup(MKID_safe(expr));
        REDIR(OT_PY_IMPL_CODE);

        /* sequence code is common for all types */
        if(TYPE_IS_SEQ_LIKE(parent_expr_type)) {
            if(optional) {
                OUT("PY_IMPL_SEQ_ATTR_GENERIC_FREE(%s, %s);\n",
                    parent_type_name, el_member_name);
                OUT("PY_IMPL_SEQ_ATTR_GENERIC_NEW(%s, %s, %s);\n",
                    parent_type_name, el_member_name, name);
            }
        }


        switch(expr->expr_type) {
        /* type defined elsewhere */
        case A1TC_REFERENCE: {
            // Each member gets its own custom getter and setter.
            ref_type_name = strdup(MKID(expr->reference->ref_expr));
            switch(parent_expr_type) {
            case ASN_CONSTR_CHOICE:
                PY_GEN_CHOICE_TYPEREF_GETSET(parent_type_name, ref_type_name,
                                             parent_struct_name, el_member_name,
                                             constr_parent_path);
                break;
            case ASN_CONSTR_SET:
                PY_GEN_SET_TYPEREF_GETSET(parent_type_name, parent_struct_name,
                                          ref_type_name, el_member_name,
                                          optional, indirect);
                break;
            case ASN_CONSTR_SEQUENCE:
                PY_GEN_SEQ_TYPEREF_GETSET(parent_type_name, ref_type_name,
                                          el_member_name, optional, indirect);
                break;
            default:
                break;
            };

            // we assume every referenced type is defined has a Python
            // candidate.
            REDIR(OT_PY_TYPE_INCLUDES);
            OUT("#include \"%s_Py.h\"\n", ref_type_name);
            break;
        }

        /* BASIC ASN-1 types */
        case ASN_BASIC_INTEGER:
            if(el_count) {
                goto embed_enumeration;
            }
            switch(parent_expr_type) {
            case ASN_CONSTR_CHOICE:
                PY_GEN_CHOICE_INTEGER_GETSET(parent_type_name,
                                             parent_struct_name, el_member_name,
                                             is_signed, constr_parent_path);
                break;
            case ASN_CONSTR_SET:
                PY_GEN_SET_INTEGER_GETSET(parent_type_name, parent_struct_name,
                                          el_member_name, optional, indirect,
                                          is_signed);
                break;
            case ASN_CONSTR_SEQUENCE:
                PY_GEN_SEQ_INTEGER_GETSET(parent_type_name, el_member_name,
                                          optional, indirect, is_signed);
                break;
            default:
                break;
            };
            break;

        case ASN_BASIC_BOOLEAN:
            switch(parent_expr_type) {
            case ASN_CONSTR_CHOICE:
                PY_GEN_CHOICE_BOOLEAN_GETSET(parent_type_name,
                                             parent_struct_name, el_member_name,
                                             constr_parent_path);
                break;
            case ASN_CONSTR_SET:
                PY_GEN_SET_BOOLEAN_GETSET(parent_type_name, parent_struct_name,
                                          el_member_name, optional, indirect);
                break;
            case ASN_CONSTR_SEQUENCE:
                PY_GEN_SEQ_BOOLEAN_GETSET(parent_type_name, el_member_name,
                                          optional, indirect);
                break;
            default:
                break;
            };
            break;

        case ASN_BASIC_UTCTime:
        case ASN_BASIC_GeneralizedTime:
        case ASN_BASIC_OCTET_STRING:
            switch(parent_expr_type) {
            case ASN_CONSTR_CHOICE:
                PY_GEN_CHOICE_BYTES_GETSET(parent_type_name, parent_struct_name,
                                           el_member_name, constr_parent_path);
                break;
            case ASN_CONSTR_SET:
                REDIR(OT_PY_IMPL_INCLUDES);
                OUT("#include <asn_codecs_prim.h>\n");

                REDIR(OT_PY_IMPL_CODE);
                PY_GEN_SET_BYTES_GETSET(parent_type_name, parent_struct_name,
                                        el_member_name, optional, indirect);
                break;
            case ASN_CONSTR_SEQUENCE:
                // will get their own implementation
                REDIR(OT_PY_IMPL_INCLUDES);
                OUT("#include <asn_codecs_prim.h>\n");

                REDIR(OT_PY_IMPL_CODE);
                PY_GEN_SEQ_BYTES_GETSET(parent_type_name, el_member_name,
                                        optional, indirect);
                break;
            default:
                break;
            };
            break;

        case ASN_BASIC_REAL: {
            int is_float32 = asn1c_expr_is_float32(expr);
            switch(parent_expr_type) {
            case ASN_CONSTR_CHOICE:
                PY_GEN_CHOICE_REAL_GETSET(parent_type_name, parent_struct_name,
                                          el_member_name, is_float32,
                                          constr_parent_path);
                break;
            case ASN_CONSTR_SET:
                PY_GEN_SET_REAL_GETSET(parent_type_name, parent_struct_name,
                                       el_member_name, optional, indirect,
                                       is_float32);
                break;
            case ASN_CONSTR_SEQUENCE:
                PY_GEN_SEQ_REAL_GETSET(parent_type_name, el_member_name,
                                       optional, indirect, is_float32);
                break;
            default:
                break;
            };
            break;
        }

        case ASN_BASIC_NULL:
            switch(parent_expr_type) {
            case ASN_CONSTR_CHOICE:
                PY_GEN_CHOICE_NULL_GETSET(parent_type_name, parent_struct_name,
                                          el_member_name, constr_parent_path);
                break;
            case ASN_CONSTR_SET:
                PY_GEN_SET_NULL_GETSET(parent_type_name, parent_struct_name,
                                       el_member_name, optional, indirect);
                break;
            case ASN_CONSTR_SEQUENCE:
                PY_GEN_SEQ_NULL_GETSET(parent_type_name, el_member_name,
                                       optional, indirect);
                break;
            default:
                break;
            };
            break;


        case ASN_BASIC_OBJECT_IDENTIFIER:
            switch(parent_expr_type) {
            case ASN_CONSTR_CHOICE:
                PY_GEN_CHOICE_OID_GETSET(parent_type_name, parent_struct_name,
                                         el_member_name, constr_parent_path);
                break;
            case ASN_CONSTR_SET:
                PY_GEN_SET_OID_GETSET(parent_type_name, parent_struct_name,
                                      el_member_name, optional, indirect);
                break;
            case ASN_CONSTR_SEQUENCE:
                PY_GEN_SEQ_OID_GETSET(parent_type_name, el_member_name,
                                      optional, indirect);
                break;
            default:
                break;
            };
            // must include new converter
            REDIR(OT_PY_TYPE_INCLUDES);
            OUT("#include \"py_convert_OBJECT_IDENTIFIER.h\"\n");
            break;

        case ASN_BASIC_BIT_STRING:
            if(el_count) goto embed_enumeration;
            switch(parent_expr_type) {
            case ASN_CONSTR_CHOICE:
                PY_GEN_CHOICE_BITSTRING_GETSET(
                    parent_type_name, parent_struct_name, el_member_name,
                    constr_parent_path);
                break;
            case ASN_CONSTR_SET:
                PY_GEN_SET_BITSTR_GETSET(parent_type_name, parent_struct_name,
                                         el_member_name, optional, indirect);
                break;
            case ASN_CONSTR_SEQUENCE:
                PY_GEN_SEQ_BITSTR_GETSET(parent_type_name, el_member_name,
                                         optional, indirect);
                break;
            default:
                break;
            };
            break;

        case ASN_BASIC_RELATIVE_OID:
            switch(parent_expr_type) {
            case ASN_CONSTR_CHOICE:
                PY_GEN_CHOICE_RELATIVE_OID_GETSET(
                    parent_type_name, parent_struct_name, el_member_name,
                    constr_parent_path);
                break;
            case ASN_CONSTR_SET:
                PY_GEN_SET_RELATIVE_OID_GETSET(
                    parent_type_name, parent_struct_name, el_member_name,
                    optional, indirect);
                break;
            case ASN_CONSTR_SEQUENCE:
                PY_GEN_SEQ_RELATIVE_OID_GETSET(parent_type_name, el_member_name,
                                               optional, indirect);
                break;
            default:
                break;
            };
            // must include new converter
            REDIR(OT_PY_TYPE_INCLUDES);
            OUT("#include \"py_convert_RELATIVE_OID.h\"\n");
            break;

        /*string types*/
        case ASN_STRING_IA5String:
        case ASN_STRING_PrintableString:
        case ASN_STRING_VisibleString:
        case ASN_STRING_ISO646String:
        case ASN_STRING_NumericString:
        case ASN_STRING_UniversalString:
        case ASN_STRING_BMPString:
        case ASN_STRING_UTF8String:
        case ASN_STRING_GeneralString:
        case ASN_STRING_GraphicString:
        case ASN_STRING_TeletexString:
        case ASN_STRING_T61String:
        case ASN_STRING_VideotexString:
        case ASN_STRING_ObjectDescriptor:
            switch(parent_expr_type) {
            case ASN_CONSTR_CHOICE:
                PY_GEN_CHOICE_STRING_GETSET(parent_type_name,
                                            parent_struct_name, el_member_name,
                                            constr_parent_path);
                break;
            case ASN_CONSTR_SET:
                PY_GEN_SET_STRING_GETSET(parent_type_name, parent_struct_name,
                                         el_member_name, optional, indirect);
                break;
            case ASN_CONSTR_SEQUENCE:
                PY_GEN_SEQ_STRING_GETSET(parent_type_name, el_member_name,
                                         optional, indirect);
                break;
            default:
                break;
            };
            break;

        case ASN_BASIC_ENUMERATED: {
        /* ENUMERATION
         * Each enumerated type will always define a new Python class (enum)
         * that stores all defined values. In contrast to pure enumeration
         * types, the name of this type will be different. The scheme is as
         * follows:
         *
         * enum_obj_type_name :=
         *      PyAsnEnum<parent_type_name>_<member_name>Object
         *
         * enum_type_obj :=
         *      PyAsnEnum<parent_type_name>_<member_name>_Type;
         */
        embed_enumeration:
            // size is len(parent_type_id) + len(tmp_member_name) + len('_') +1
            enum_member_name_len =
                strlen(parent_type_name) + strlen(el_member_name) + 2;
            constr_enum_name = (char *)malloc(enum_member_name_len);
            snprintf(constr_enum_name, enum_member_name_len, "%s_%s",
                     parent_type_name, el_member_name);

            REDIR(OT_PY_TYPE_DECLS);
            OUT("PyCompat_DEF_ENUM(%s);\n", constr_enum_name);

            /* the type object MUST be initialized with NULL */
            REDIR(OT_PY_IMPL_CODE);
            OUT("PyObject *PyAsnEnum%s_Type = NULL;\n", constr_enum_name);

            // std enum conversion
            switch(parent_expr_type) {
            case ASN_CONSTR_CHOICE:
                if(is_bitstr) {
                    PY_GEN_CHOICE_NAMED_BITSTRING_GETSET(
                        parent_type_name, parent_struct_name, el_member_name,
                        constr_enum_name, constr_parent_path);
                    break;
                } else {
                    PY_GEN_CHOICE_ENUM_GETSET(
                        parent_type_name, parent_struct_name, el_member_name,
                        constr_enum_name, is_signed, constr_parent_path);
                }
                break;
            case ASN_CONSTR_SET:
                if(is_bitstr) {
                    PY_GEN_SET_NAMED_BITSTR_GETSET(
                        parent_type_name, parent_struct_name, el_member_name,
                        constr_enum_name, optional, indirect);
                } else {
                    PY_GEN_SET_ENUM_GETSET(parent_type_name, parent_struct_name,
                                           el_member_name, constr_enum_name,
                                           is_signed, optional, indirect);
                }
            case ASN_CONSTR_SEQUENCE:
                if(is_bitstr) {
                    PY_GEN_SEQ_NAMED_BITSTR_GETSET(
                        parent_type_name, el_member_name, constr_enum_name,
                        optional, indirect);
                } else {
                    PY_GEN_SEQ_ENUM_GETSET(parent_type_name, el_member_name,
                                           constr_enum_name, is_signed,
                                           optional, indirect);
                }
                break;
            default:
                break;
            }

            /* module init */
            REDIR(OT_PY_IMPL_CODE_MOD_CLEAR);
            INDENTED(OUT("Py_CLEAR(PyAsnEnum%s_Type);\n", constr_enum_name));

            REDIR(OT_PY_IMPL_CODE_MOD_INIT);
            INDENT(+1);
            OUT("PY_IMPL_NEW_ENUM(%s.%s_VALUES, PyAsnEnum%s_Type, -1, \n",
                parent_type_name, el_member_name, constr_enum_name);
            INDENT(+1);
            TQ_FOR(v, &(expr->members), next) {
                switch(v->expr_type) {
                case A1TC_UNIVERVAL:
                    tmp_name = c_member_name(arg, v);
                    OUT("PY_IMPL_ENUM_VALUE(%s, %s, %s);\n", tmp_name, tmp_name,
                        asn1p_itoa(is_bitstr ? (1 << v->value->value.v_integer)
                                             : v->value->value.v_integer));
                    break;
                case A1TC_EXTENSIBLE:
                    OUT("/*\n");
                    OUT(" * Enumeration is extensible\n");
                    OUT(" */\n");
                    break;
                default:
                    return -1;
                }
            };
            INDENT(-1);
            OUT(");\n");
            OUT("PY_IMPL_ASSIGN_ENUM_DIRECT(%s, %s, %s_VALUES);\n",
                parent_type_name, constr_enum_name, el_member_name);
            INDENT(-1);
            break;
        }

        default:
            break;
        }
    } else {
        name = strdup(MKID(expr));
        PY_GEN_DEFAULT_INCLUDE();
        /* This is a simple type alias: */
        REDIR(OT_PY_TYPE_DECLS);
        OUT("PyCompat_DEF_STRUCT(%s);\n", name);
        OUT("PyCompat_DEF_TYPE(%s);\n", name);
        if(expr->expr_type == ASN_BASIC_ENUMERATED || el_count) {
            /* Simple enumerations will be created lazily */
            OUT("typedef PyObject PyAsnEnum%sObject;\n", name);
            OUT("extern PyObject *PyAsnEnum%s_Type;\n", name);
        }
        /* some type converters are built-in*/
        REDIR(OT_PY_TYPE_CONVERT);
        switch(expr->expr_type) {
        case ASN_BASIC_INTEGER: {
            // if this integer has named parts, convert it to an enum
            if(el_count) {
                goto basic_enumeration;
            }

            // conversion is made easy
            PY_GEN_ASNTYPE_TOPY_INLINE(name);
            if(asn1c_type_fits_long(arg, expr) == FL_FITS_UNSIGN) {
                OUT("return PyCompatLong_FromSize_t(*pSrc);\n");
            } else {
                OUT("return PyCompatLong_FromSsize_t(*pSrc);\n");
            }
            PY_GEN_END_FUNC();

            PY_GEN_ASNTYPE_FROMPY_INLINE(name);
            OUT("PyCompatLong_Check(pObj, -1);\n");
            if(asn1c_type_fits_long(arg, expr) == FL_FITS_UNSIGN) {
                OUT("*pDst = (%s)PyCompatLong_AsSize_t(pObj);\n", name);
            } else {
                OUT("*pDst = (%s_t)PyCompatLong_AsSsize_t(pObj);\n", name);
            }
            OUT("return 0;\n");
            PY_GEN_END_FUNC();

            /*implementation*/
            PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);


            /*module init*/
            PY_GEN_MOD_BASIC(name);
            break;
        }
        case ASN_BASIC_BOOLEAN: {
            // conversion is made easy
            PY_GEN_ASNTYPE_TOPY_INLINE(name);
            OUT("return PyCompatBool_FromLong(*pSrc);\n");
            PY_GEN_END_FUNC();

            PY_GEN_ASNTYPE_FROMPY_INLINE(name);
            // we actually don't need this
            // OUT("PyCompatBool_Check(pObj, -1);\n");
            OUT("*pDst = (%s_t)PyCompatBool_AsLong(pObj);\n", name);
            OUT("return 0;\n");
            PY_GEN_END_FUNC();

            /*implementation*/
            PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

            /*module init*/
            PY_GEN_MOD_BASIC(name);
            break;
        }
        case ASN_BASIC_REAL: {
            int is_float32 = asn1c_expr_is_float32(expr);
            PY_GEN_ASNTYPE_TOPY_INLINE(name);
            OUT("return PyCompatFloat_AsObject((void *)pSrc, %d);\n",
                is_float32);
            PY_GEN_END_FUNC();

            PY_GEN_ASNTYPE_FROMPY_INLINE(name);
            OUT("return PyCompatFloat_FromObject(pObj, (void *)pDst, %d);\n",
                is_float32);
            PY_GEN_END_FUNC();

            /*implementation*/
            PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

            /*module init*/
            PY_GEN_MOD_BASIC(name);
            break;
        }
        case ASN_BASIC_NULL: {
            PY_GEN_ASNTYPE_TOPY_INLINE(name);
            OUT("return PyCompatNull_FromLong(*pSrc);\n");
            PY_GEN_END_FUNC();

            PY_GEN_ASNTYPE_FROMPY_INLINE(name);
            OUT("*pDst = (%s_t)PyCompatNull_AsLong(pObj);\n", name);
            OUT("return 0;\n");
            PY_GEN_END_FUNC();

            /*implementation*/
            PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

            /*module init*/
            PY_GEN_MOD_BASIC(name);
            break;
        }
        case ASN_BASIC_BIT_STRING: {
            PY_GEN_ASNTYPE_FROMPY_INLINE(name);
            if(el_count) {
                OUT("return PyCompatFlag_FromObject(pObj, &pDst->buf, "
                    "&pDst->size);\n");
            } else {
                OUT("return PyCompatBitArray_ToStringAndSize(pObj, &pDst->buf, "
                    "&pDst->size);\n");
            }
            PY_GEN_END_FUNC();

            PY_GEN_ASNTYPE_TOPY_INLINE(name);
            if(el_count) {
                OUT("return PyCompatFlag_AsObject(PyAsnEnum%s_Type, (const "
                    "char *)pSrc->buf, pSrc->size);\n",
                    name);
            } else {
                OUT("return PyCompatBitArray_FromStringAndSize(pSrc->buf, "
                    "pSrc->size);\n");
            }
            PY_GEN_END_FUNC();

            /*implementation*/
            PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

            /*module init*/
            REDIR(OT_PY_IMPL_CODE_MOD_SETUP);
            INDENTED(PY_GEN_MOD_SETUP_SINGLE(name));

            if(el_count) {
                REDIR(OT_PY_IMPL_CODE);
                OUT("PyObject *PyAsnEnum%s_Type = NULL;\n", name);

                REDIR(OT_PY_IMPL_CODE_MOD_CLEAR);
                INDENTED(OUT("Py_CLEAR(PyAsnEnum%s_Type);\n", name));

                REDIR(OT_PY_IMPL_CODE_MOD_INIT);
                INDENT(+1);
                OUT("PY_IMPL_NEW_ENUM_TYPE(PyIntFlag_Type, %s.VALUES, "
                    "PyAsnEnum%s_Type, -1, \n",
                    name, name);
                INDENT(+1);
                TQ_FOR(v, &(expr->members), next) {
                    switch(v->expr_type) {
                    case A1TC_UNIVERVAL:
                        tmp_name = c_member_name(arg, v);
                        OUT("PY_IMPL_ENUM_VALUE(%s, %s, %s);\n", tmp_name,
                            tmp_name,
                            asn1p_itoa(1 << v->value->value.v_integer));
                        break;
                    case A1TC_EXTENSIBLE:
                        OUT("/*\n");
                        OUT(" * Enumeration is extensible\n");
                        OUT(" */\n");
                        break;
                    default:
                        return -1;
                    }
                };
                INDENT(-1);
                OUT(");\n");
                OUT("PY_IMPL_ASSIGN_ENUM(%s);\n", MKID(expr));
                INDENT(-1);
            }

            REDIR(OT_PY_IMPL_CODE_MOD_INIT);
            INDENTED(PY_GEN_MOD_INIT_SINGLE(MKID(expr)));
            break;
        }

        case ASN_BASIC_OBJECT_IDENTIFIER: { /* for now, use special
                                               converter*/
            PY_GEN_ASNTYPE_FROMPY_INLINE(name);
            OUT("return PyCompatOID_FromUnicode(pObj, pDst);");
            PY_GEN_END_FUNC();

            PY_GEN_ASNTYPE_TOPY_INLINE(name);
            OUT("return PyCompatOID_AsUTF8String(pSrc);");
            PY_GEN_END_FUNC();

            /*default generic implementation*/
            PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

            /*module init*/
            PY_GEN_MOD_BASIC(name);

            // must include new converter
            REDIR(OT_PY_TYPE_INCLUDES);
            OUT("#include \"py_convert_OBJECT_IDENTIFIER.h\"\n");
            break;
        }
        case ASN_BASIC_RELATIVE_OID: { /* for now, use special converter*/
            printf("RELATIVE_OID\n");
            PY_GEN_ASNTYPE_FROMPY_INLINE(name);
            OUT("return PyCompatRelativeOID_FromUnicode(pObj, pDst);");
            PY_GEN_END_FUNC();

            PY_GEN_ASNTYPE_TOPY_INLINE(name);
            OUT("return PyCompatRelativeOID_AsUTF8String(pSrc);");
            PY_GEN_END_FUNC();

            /*default generic implementation*/
            PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

            /*module init*/
            PY_GEN_MOD_BASIC(name);

            // must include new converter
            REDIR(OT_PY_TYPE_INCLUDES);
            OUT("#include \"py_convert_RELATIVE_OID.h\"\n");
            break;
        }

        /*Bytes types*/
        case ASN_BASIC_UTCTime:
        case ASN_BASIC_GeneralizedTime:
        case ASN_BASIC_OCTET_STRING: {
            PY_GEN_ASNTYPE_FROMPY_INLINE(name);
            OUT("return PyCompatBytes_ToStringAndSize(pObj, &pDst->buf, "
                "&pDst->size);");
            PY_GEN_END_FUNC();

            PY_GEN_ASNTYPE_TOPY_INLINE(name);
            OUT("return PyCompatBytes_FromStringAndSize(pSrc->buf, "
                "pSrc->size);");
            PY_GEN_END_FUNC();

            /*implementation*/
            PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

            /*module init*/
            PY_GEN_MOD_BASIC(name);
            break;
        }

        /*string types*/
        case ASN_STRING_IA5String:
        case ASN_STRING_PrintableString:
        case ASN_STRING_VisibleString:
        case ASN_STRING_ISO646String:
        case ASN_STRING_NumericString:
        case ASN_STRING_UniversalString:
        case ASN_STRING_BMPString:
        case ASN_STRING_UTF8String:
        case ASN_STRING_GeneralString:
        case ASN_STRING_GraphicString:
        case ASN_STRING_TeletexString:
        case ASN_STRING_T61String:
        case ASN_STRING_VideotexString:
        case ASN_STRING_ObjectDescriptor: {
            PY_GEN_ASNTYPE_FROMPY_INLINE(name);
            OUT("pDst->buf = (uint8_t "
                "*)PyCompatUnicode_AsUTF8AndSize(pObj, "
                "&pDst->size);\n");
            OUT("return pDst->buf ? 0 : -1;\n");
            PY_GEN_END_FUNC();

            PY_GEN_ASNTYPE_TOPY_INLINE(name);
            OUT("return PyCompatUnicode_FromStringAndSize(pSrc->buf, "
                "pSrc->size);\n");
            PY_GEN_END_FUNC();

            /*implementation*/
            PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

            /*module init*/
            PY_GEN_MOD_BASIC(name);
            break;
        }

        case ASN_BASIC_ENUMERATED: {
        basic_enumeration:
            PY_GEN_ASNTYPE_FROMPY_INLINE(name);
            OUT("return PyCompatEnum_FromObject(pObj, (void *)pDst, %d);\n",
                is_signed);
            PY_GEN_END_FUNC();

            PY_GEN_ASNTYPE_TOPY_INLINE(name);
            if(asn1c_type_fits_long(arg, expr) == FL_FITS_UNSIGN) {
                OUT("return "
                    "PyCompatEnum_FromSize_t(PyAsnEnum%s_Type,*pSrc);\n",
                    name);
            } else {
                OUT("return PyCompatEnum_FromSsize_t(PyAsnEnum%s_Type, "
                    "*pSrc);\n",
                    name);
            }
            PY_GEN_END_FUNC();

            /*implementation for base type*/
            PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);
            REDIR(OT_PY_IMPL_CODE);
            OUT("PyObject *PyAsnEnum%s_Type = NULL;\n", name);

            /*implementation for enum type*/
            REDIR(OT_PY_IMPL_CODE_MOD_SETUP);
            INDENT(+1);
            PY_GEN_MOD_SETUP_SINGLE(name);  // single type here

            /* clear out the referenced enum type*/
            REDIR(OT_PY_IMPL_CODE_MOD_CLEAR);
            OUT("Py_CLEAR(PyAsnEnum%s_Type);\n", name);
            INDENT(-1);

            /*module init*/
            REDIR(OT_PY_IMPL_CODE_MOD_INIT);
            INDENT(+1);
            OUT("PY_IMPL_NEW_ENUM(%s.VALUES, PyAsnEnum%s_Type, -1, \n", name,
                name);
            INDENT(+1);
            TQ_FOR(v, &(expr->members), next) {
                switch(v->expr_type) {
                case A1TC_UNIVERVAL:
                    tmp_name = c_member_name(arg, v);
                    OUT("PY_IMPL_ENUM_VALUE(%s, %s, %s);\n", tmp_name, tmp_name,
                        asn1p_itoa(v->value->value.v_integer));
                    break;
                case A1TC_EXTENSIBLE:
                    OUT("/*\n");
                    OUT(" * Enumeration is extensible\n");
                    OUT(" */\n");
                    break;
                default:
                    return -1;
                }
            };
            INDENT(-1);
            OUT(");\n");

            OUT("PY_IMPL_ASSIGN_ENUM(%s);\n", name);
            PY_GEN_MOD_ADD_OBJECT(name);
            INDENT(-1);

            break;
        }

        default: {
            printf("Unknown type %d\n", expr->expr_type);
            PY_GEN_ASNTYPE_FROMPY(name);
            PY_GEN_ASNTYPE_TOPY(name);
            break;
        }
        }
    }

    REDIR(saved_target);
    ASN_XFREE(parent_type_name);
    ASN_XFREE(parent_struct_name);
    ASN_XFREE(ref_type_name);
    ASN_XFREE(el_member_name);
    ASN_XFREE(name);
    ASN_XFREE(constr_enum_name);
    return 0;
}

/* static functions */
static inline int
asn1c_expr_is_float32(asn1p_expr_t *expr) {
    asn1cnst_range_t *range = asn1constraint_compute_OER_range(
        expr->Identifier, ASN_BASIC_REAL, expr->combined_constraints,
        ACT_EL_RANGE, 0, 0, 0);
    int is_float32 = range->narrowing == NARROW_FLOAT32;
    asn1constraint_range_free(range);
    return is_float32;
}

static char *
py_type_name(arg_t *arg, asn1p_expr_t *expr, int flags) {
    /* NAMING SCHEME:
     * The basic naming scheme should be following the parent's type name:
     *
     * <type_name> := [ <parent_type_name> '_' ] <type_name> [ '_' <anon_name>]
     * <anon_name> := '_ANON_' <anon_number>
     */
    char *constr_type_name = NULL, *tmp_name = strdup(MKID(expr)),
         *tmp_parent_name = NULL;
    size_t tmp_len = 0;
    asn1p_expr_t *parent = expr->parent_expr;

    while(parent && arg->embed) {
        if(!parent->parent_expr) {
            // got root type
            tmp_parent_name = strdup(MKID(parent));
            break;
        }
        parent = parent->parent_expr;
    }

    if(tmp_parent_name) {
        tmp_len = strlen(tmp_parent_name) + strlen(tmp_name) + 2;
        constr_type_name = malloc(tmp_len);
        snprintf(constr_type_name, tmp_len, "%s%c%s", tmp_parent_name,
                 (flags & PYTNF_CLASS) ? '.' : '_', tmp_name);
    } else {
        constr_type_name = strdup(tmp_name);
    }

    ASN_CLEAR(tmp_name);
    if((arg->embed == 1 && (flags & PYTNF_CONSTR)) || arg->embed > 1) {
        // anonymous type
        tmp_name = constr_type_name;
        tmp_len = strlen(constr_type_name) + 7 + 20;
        constr_type_name = malloc(tmp_len);
        snprintf(constr_type_name, tmp_len, "%s_ANON_%d", tmp_name,
                 expr->_type_unique_index);
    }
    ASN_XFREE(tmp_parent_name);
    ASN_XFREE(tmp_name);
    return constr_type_name;
}

static char *
get_py_class_name(arg_t *arg, asn1p_expr_t *expr) {
    asn1p_expr_t *parent = expr->parent_expr;
    char *constr_type_name = NULL, *tmp_name = NULL, *tmp_parent_name = NULL;
    size_t tmp_len = 0, cur_len = 0;
    int has_parent = 0;

    constr_type_name = strdup(MKID(expr));
    cur_len = strlen(constr_type_name);

    while(parent && arg->embed) {
        has_parent = parent->parent_expr ? 1 : 0;
        tmp_parent_name = strdup(MKID(parent));
        tmp_name = constr_type_name;
        tmp_len = strlen(tmp_parent_name) + cur_len + 1 + (has_parent ? 5 : 0);
        constr_type_name = malloc(tmp_len + 1);


        snprintf(constr_type_name, tmp_len + 1, "%s%s.%s", tmp_parent_name,
                 has_parent ? "_TYPE" : "", tmp_name);
        ASN_XFREE(tmp_name);
        ASN_XFREE(tmp_parent_name);
        parent = parent->parent_expr;
        cur_len = tmp_len;
        constr_type_name[tmp_len] = '\0';
    }

    if(arg->embed) {
        tmp_len = cur_len + 5;
        tmp_name = constr_type_name;
        constr_type_name = malloc(tmp_len + 1);
        snprintf(constr_type_name, tmp_len + 1, "%s_TYPE", tmp_name);
        ASN_FREE(tmp_name);
        constr_type_name[tmp_len] = '\0';
    }

    return constr_type_name;
}

static char *
py_parent_type_name(arg_t *arg, asn1p_expr_t *expr) {
    char *tmp_name = NULL;
    asn1p_expr_t *parent = expr->parent_expr;
    while(parent && arg->embed) {
        if(!parent->parent_expr) {
            // got root type
            tmp_name = strdup(MKID(parent));
            break;
        }
        parent = parent->parent_expr;
    }
    return tmp_name;
}

static size_t
asn1c_get_member_index(arg_t *arg, asn1p_expr_t *expr, const char *name) {
    size_t index = 0;
    asn1p_expr_t *v = NULL;
    TQ_FOR(v, &(expr->members), next) {
        /* first, test for raw identifier , then test for safe identifier */
        if(strcmp(name, v->Identifier) == 0) return index;
        if(strcmp(name, MKID_safe(v)) == 0) return index;
        ++index;
    }
    return index;
}

static char *
py_get_anonymous_type_def(arg_t *arg, asn1p_expr_t *expr, const char *name) {
    /* Find a path to the anonymous type definition */
    asn1p_expr_t *parent = NULL;
    char *tmp_name = NULL, *constr_path = NULL;
    size_t index = 0, tmp_len = 0, cur_len = 0, cur_alloc = 0;

    parent = expr->parent_expr;
    if(!parent) {
        return NULL;
    }

    /* fetch the parent index */
    index = asn1c_get_member_index(arg, parent, name);
    if(parent->parent_expr == NULL) {
        /* only one layer:
         * <path> := 'asn_DEF' <parent_name> '.elements[' <index> '].type'
         */
        tmp_name = strdup(MKID(parent));
        tmp_len = strlen(tmp_name) + 24 + ASN1C_MAX_INT_WIDTH;
        constr_path = malloc(tmp_len);
        snprintf(constr_path, tmp_len, "asn_DEF_%s.elements[%ld].type",
                 tmp_name, index);
        ASN_FREE(tmp_name);
    } else {
        constr_path = malloc(256);
        cur_len = 0;
        cur_alloc = 256;
        memset(constr_path, 0, 256);

        while(parent->parent_expr != NULL) {
            /* <path> := '->elements[' <index> '].type */
            tmp_len = cur_len + 24 + ASN1C_MAX_INT_WIDTH;
            if(tmp_len > cur_alloc) {
                constr_path = realloc(constr_path, tmp_len);
                memset(constr_path + cur_len, 0, tmp_len - cur_len);
                cur_alloc = tmp_len;
            }
            tmp_name = strdup(constr_path);
            snprintf(constr_path, tmp_len, "->elements[%ld].type%s", index,
                     cur_len ? tmp_name : "");
            cur_len = tmp_len;
            ASN_FREE(tmp_name);

            tmp_name = strdup(MKID(parent));
            parent = parent->parent_expr;
            index = asn1c_get_member_index(arg, parent, tmp_name);
            ASN_FREE(tmp_name);
        }

        tmp_len = cur_len + 24 + ASN1C_MAX_INT_WIDTH;
        if(tmp_len > cur_alloc) {
            constr_path = realloc(constr_path, tmp_len);
            memset(constr_path + cur_len, 0, tmp_len - cur_len);
            cur_alloc = tmp_len;
        }
        tmp_name = strndup(constr_path, cur_len);
        snprintf(constr_path, tmp_len, "asn_DEF_%s.elements[%ld].type%s",
                 MKID(parent), index, tmp_name);
        ASN_FREE(tmp_name);
    }
    return constr_path;
}

static int
expr_elements_count(arg_t *arg, asn1p_expr_t *expr) {
    asn1p_expr_t *topmost_parent;
    asn1p_expr_t *v;
    int elements = 0;

    topmost_parent = WITH_MODULE_NAMESPACE(
        expr->module, expr_ns,
        asn1f_find_terminal_type_ex(arg->asn, expr_ns, expr));
    if(!topmost_parent) return 0;

    if(!(topmost_parent->expr_type & ASN_CONSTR_MASK)
       && !(topmost_parent->expr_type == ASN_BASIC_INTEGER)
       && !(topmost_parent->expr_type == ASN_BASIC_ENUMERATED)
       && !(topmost_parent->expr_type == ASN_BASIC_BIT_STRING))
        return 0;

    TQ_FOR(v, &(topmost_parent->members), next) {
        if(v->expr_type != A1TC_EXTENSIBLE) elements++;
    }

    return elements;
}

#endif /* ASN1_COMPILER_LANDUAGE_PY_H */