#include "asn1c_internal.h"
#include "asn1c_Py.h"
#include "asn1c_out.h"
#include "asn1c_misc.h"
#include "asn1c_naming.h"
#include "asn1c_py_out.h"

#include <asn1parser.h>
#include <asn1print.h>
#include <asn1fix_crange.h> /* constraint groker from libasn1fix */
#include <asn1fix_export.h> /* other exportables from libasn1fix */

#define MKID(expr) (asn1c_make_identifier(AMI_USE_PREFIX, expr, 0))
#define MKID_safe(expr) (asn1c_make_identifier(AMI_CHECK_RESERVED, expr, 0))

#define TYPE_IS_SIGNED(arg, expr) \
    (asn1c_type_fits_long(arg, expr) != FL_FITS_UNSIGN)
#define TYPE_IS_UNION(expr) (expr) && (expr->expr_type == ASN_CONSTR_CHOICE)
#define TYPE_IS_FLOAT(expr) (asn1c_expr_is_float32(expr))
#define TYPE_IS_SEQ_LIKE(expr_type) \
    ((expr_type) == ASN_CONSTR_SEQUENCE || (expr_type) == ASN_CONSTR_SET)
#define TYPE_IS_SEQ_OF_LIKE(expr_type) \
    ((expr_type) == ASN_CONSTR_SEQUENCE_OF || (expr_type) == ASN_CONSTR_SET_OF)
#define TYPE_IS_SET(expr) (expr) && (expr->expr_type == ASN_CONSTR_SET)
#define TYPE_IS_CONSTR(expr)                           \
    ((expr) && (expr->expr_type >= ASN_CONSTR_MASK) && \
     (expr->expr_type <= ASN_CONSTR_OPEN_TYPE))
#define TYPE_IS_OPTIONAL(expr) \
    ((expr) && (expr->marker.flags & EM_OPTIONAL) == EM_OPTIONAL)
#define TYPE_IS_INDIRECT(expr) \
    ((expr) && (expr->marker.flags & EM_INDIRECT) == EM_INDIRECT)

#define TYPE_IS_IMPORTED(arg, expr)                   \
    ((arg)->flags & A1C_SKIP_IMPORTS &&               \
     !((expr)->module->_tags & MT_STANDARD_MODULE) && \
     !((expr)->module->_tags & MT_FIRST_MODULE))

#define ASN1C_MAX_INT_WIDTH 20

enum {
    PYTNF_NONE = 0x00,
    PYTNF_CONSTR = 0x01,
    PYTNF_CLASS = 0x02,
};

static const char *PY_TYPE_MAP[] = {
    [ASN_TYPE_ANY] = "bytes",
    [ASN_BASIC_INTEGER] = "int",
    [ASN_BASIC_BIT_STRING] = "EXT_bitarray",
    [ASN_BASIC_OCTET_STRING] = "bytes",
    [ASN_BASIC_NULL] = "None",
    [ASN_BASIC_BOOLEAN] = "bool",
    [ASN_BASIC_REAL] = "float",
    [ASN_BASIC_CHARACTER_STRING] = "str",
    [ASN_BASIC_OBJECT_IDENTIFIER] = "str",
    [ASN_BASIC_RELATIVE_OID] = "str",
    [ASN_BASIC_UTCTime] = "bytes",
    [ASN_BASIC_GeneralizedTime] = "bytes",
    [ASN_STRING_IA5String] = "str",
    [ASN_STRING_PrintableString] = "str",
    [ASN_STRING_VisibleString] = "str",
    [ASN_STRING_ISO646String] = "str",
    [ASN_STRING_NumericString] = "str",
    [ASN_STRING_UniversalString] = "str",
    [ASN_STRING_BMPString] = "str",
    [ASN_STRING_UTF8String] = "str",
    [ASN_STRING_GeneralString] = "str",
    [ASN_STRING_GraphicString] = "str",
    [ASN_STRING_TeletexString] = "str",
    [ASN_STRING_T61String] = "str",
    [ASN_STRING_VideotexString] = "str",
    [ASN_STRING_ObjectDescriptor] = "str",
    [ASN_EXPR_TYPE_MAX] = NULL,
};

/**
 * @brief Builds a path string that references an anonymous type definition
 * in C (as generated by the ASN.1 compiler), like:
 *
 *      asn_DEF_<parent>.elements[<index>].type
 *
 * Or, for nested anonymous types:
 *
 *      asn_DEF_<grandparent>.elements[<parent_index>].type->elements[<index>].type
 */
static char *py_get_anonymous_type_def(arg_t *arg, asn1p_expr_t *expr,
                                       const char *name);
static int asn1c_expr_is_float32(asn1p_expr_t *expr);
static char *py_type_name(arg_t *arg, asn1p_expr_t *expr, int flags);
static char *get_py_class_name(arg_t *arg, asn1p_expr_t *expr);
static char *py_parent_type_name(arg_t *arg, asn1p_expr_t *expr);
static size_t asn1c_get_member_index(arg_t *arg, asn1p_expr_t *expr,
                                     const char *name);
static int expr_elements_count(arg_t *arg, asn1p_expr_t *expr);
static int asn1c_lang_Py_type_CONSTR(arg_t *arg, struct c_names *pre_cn);
static int asn1c_lang_Py_stubs_generate_init(arg_t *arg);
static int asn1c_lang_Py_member(arg_t *arg, asn1p_expr_t *memb,
                                asn1p_expr_t *parent_expr);
static asn1p_expr_t *asn1c_get_REFERENCE(arg_t *arg, asn1p_expr_t *expr);

/* global functions */
int asn1c_lang_Py_type_SEQUENCE(arg_t *arg) {
    struct c_names ns;
    asn1p_expr_t *expr;
    asn1p_expr_t *v;

    char *type_name;
    char *constr_struct_name;
    char *py_class_name;
    char *parent_type_name;
    char *inner_parent_name;
    char *constr_path;
    char *constr_member_name;

    int saved_target;
    int saved_indent;

    expr = arg->expr;
    v = NULL;
    ns = c_name(arg);
    type_name = py_type_name(arg, expr, PYTNF_CONSTR);
    constr_struct_name = strdup(ns.base_name);
    constr_member_name = strdup(ns.as_member);
    py_class_name = get_py_class_name(arg, expr);
    parent_type_name = py_parent_type_name(arg, expr);
    inner_parent_name = NULL;
    constr_path = NULL;
    saved_target = arg->target->target;
    saved_indent = INDENT_LEVEL;

    PY_GEN_DEFAULT_INCLUDE();
    /* type def */
    REDIR(OT_PY_TYPE_DECLS);
    if (arg->embed) {
        OUT("PyCompat_DEF_ANON_STRUCT(%s, %s);\n", type_name,
            constr_struct_name);
        OUT("PyCompat_DEF_TYPE(%s);\n", type_name);
        // this is debateable:
        // OUT("typedef struct %s %s_t;\n", constr_struct_name,
        //     constr_struct_name);
        constr_path = py_get_anonymous_type_def(arg, expr, constr_member_name);
        assert(constr_path);

        if (arg->embed > 1) {
            inner_parent_name =
                py_type_name(arg, expr->parent_expr, PYTNF_CONSTR);
        }
    } else {
        PY_GEN_DEF_TYPE(type_name);
    }

    /* type converters */
    REDIR(OT_PY_TYPE_CONVERT);
    if (arg->embed) {
        OUT("int PyAsn%s_FromPython(PyObject *pObj, %s_t *pDst);\n", type_name,
            type_name);
        OUT("PyObject *PyAsn%s_ToPython(%s_t *pSrc, PyObject *parent);\n",
            type_name, type_name);
    } else {
        PY_GEN_ASNTYPE_FROMPY(type_name);
        PY_GEN_ASNTYPE_TOPY(type_name);
    }

    REDIR(OT_PY_IMPL_CODE);
    /* make sure we capture all class fields*/
    TQ_FOR (v, &(expr->members), next) {
        if (asn1c_lang_Py_member(arg, v, expr) < 0) return -1;
    }
    /* needs to be refreshed */

    /* default methods */
    if (arg->embed) {
        OUT("PY_IMPL_CHECK_CONSTRAINTS(%s, %s);\n", type_name, constr_path);
        OUT("PY_IMPL_ENCODE(%s, %s);\n", type_name, constr_path);
        OUT("PY_IMPL_DECODE(%s, %s);\n", type_name, constr_path);
        /*
         * DEALLOC is a bit special as it requires us to dereference the
         * type_DEF pointer.
         */
        OUT("PY_IMPL_DEALLOC(%s, *(%s));\n", type_name, constr_path);
        OUT("PY_IMPL_SEQ_TOPY(%s, %s);\n", type_name, constr_path);
    } else {
        PY_GEN_TYPE_DEALLOC(type_name);
        PY_GEN_TYPE_CHECK_CONSTRAINTS(type_name);
        PY_GEN_TYPE_ENCODE(type_name);
        PY_GEN_TYPE_DECODE(type_name);
        OUT("PY_IMPL_SEQ_GENERIC_TOPY(%s);\n", type_name);
    }
    PY_GEN_TYPE_PARSERS(type_name);

    /* next methods are shared */
    PY_GEN_TYPE_NEW(type_name, !arg->embed);
    PY_GEN_TYPE_REPR(type_name);
    PY_GEN_TYPE_IS_VALID(type_name);
    OUT("PY_IMPL_SEQ_FROMPY(%s,\n", type_name);
    INDENT(+1);
    TQ_FOR (v, &(expr->members), next) {
        if (v->expr_type == A1TC_EXTENSIBLE) continue;
        if (expr->expr_type == ASN_CONSTR_SET) {
            OUT("PY_IMPL_SET_INIT_ATTR(%s, %s, %s);\n", type_name,
                constr_member_name, MKID_safe(v));
        } else {
            OUT("PY_IMPL_SEQ_INIT_ATTR(%s, %s);\n", type_name, MKID_safe(v));
        }
    }
    INDENT(-1);
    OUT(");\n");
    OUT("PY_IMPL_SEQ_INIT(%s);\n", type_name);
    if (arg->embed) {
        if (asn1c_lang_Py_type_CONSTR(arg, NULL) < 0) {
            return -1;
        }
    }

    /* methods for SEQ objects will be the same */
    REDIR(OT_PY_IMPL_METHODS);
    PY_GEN_TYPE_METHODS_BEGIN(type_name);
    PY_GEN_TYPE_DEFAULT_METHODS(type_name);
    PY_GEN_TYPE_METHODS_END();

    /* members according to the ASN.1 type */
    REDIR(OT_PY_IMPL_ATTRS);
    PY_GEN_TYPE_ATTRS_BEGIN(type_name);
    TQ_FOR (v, &(expr->members), next) {
        if (v->expr_type == A1TC_EXTENSIBLE) continue;
        PY_GEN_TYPE_ATTRSTR(type_name, MKID_safe(v));
    }
    PY_GEN_TYPE_ATTRS_END();

    /* type spec */
    REDIR(OT_PY_IMPL_CLASS);
    PY_GEN_CLASS_BEGIN_INTERNAL(arg->pymodule_qualname, type_name,
                                py_class_name);
    if (arg->embed) {
        PY_GEN_CLASS_DOC(
            "ASN.1 anonymous type %s_TYPE part of %s", constr_struct_name,
            arg->embed > 1 ? MKID(expr->parent_expr) : parent_type_name);
    } else {
        PY_GEN_CLASS_DOC("ASN.1 %s type", py_class_name);
    }
    PY_GEN_CLASS_END();

    /* mod init */
    REDIR(OT_PY_IMPL_CODE_MOD_SETUP);
    INDENTED(PY_GEN_MOD_SETUP_SINGLE(type_name));
    REDIR(OT_PY_IMPL_CODE_MOD_INIT);
    if (arg->embed == 1) {
        INDENTED(OUT("PY_IMPL_MOD_ASSIGN_OBJECT(%s, %s_TYPE, &PyAsn%s_Type);\n",
                     parent_type_name, constr_member_name, type_name));
    } else if (arg->embed == 0) {
        INDENTED(PY_GEN_MOD_INIT_SINGLE(type_name));
    } else {
        /* this could be used to set the new type into another anonymous SEQ */
        INDENTED(OUT("PY_IMPL_MOD_ASSIGN_OBJECT(%s, %s_TYPE, &PyAsn%s_Type);\n",
                     inner_parent_name, constr_member_name, type_name));
    }

    if (!arg->embed) {
        PY_GEN_TYPE_MOD_INIT(type_name);
        PY_GEN_MODULE_ADD_TYPE(
            type_name, asn1c_make_identifier(
                           AMI_USE_PREFIX | AMI_MASK_ONLY_SPACES, expr, NULL));
    }

    if (!TYPE_IS_IMPORTED(arg, arg->expr)) {
        if (asn1c_lang_Py_stubs_generate_init(arg) < 0) return -1;
        PY_GEN_STUBS_BEGIN;
        PY_GEN_LF;
        PY_GEN_STUBS_EMBED_CONSTR(constr_member_name, expr);
        PY_GEN_STUBS_END;
    }

    ASN_XFREE(type_name);
    ASN_XFREE(constr_struct_name);
    ASN_XFREE(py_class_name);
    ASN_XFREE(parent_type_name);
    ASN_XFREE(inner_parent_name);
    ASN_XFREE(constr_member_name);
    REDIR(saved_target);
    return 0;
}

int asn1c_lang_Py_type_CHOICE(arg_t *arg) {
    struct c_names ns;
    asn1p_expr_t *expr = arg->expr;
    asn1p_expr_t *v;

    char *type_name;
    char *constr_struct_name;
    char *py_class_name;
    char *parent_type_name;
    char *inner_parent_name;
    char *constr_path;
    char *constr_member_name;

    int saved_target;
    int saved_indent;
    size_t presence_value = 0;

    ns = c_name(arg);
    type_name = py_type_name(arg, expr, PYTNF_CONSTR);
    constr_struct_name = strdup(ns.base_name);
    constr_member_name = strdup(ns.as_member);
    py_class_name = get_py_class_name(arg, expr);
    parent_type_name = py_parent_type_name(arg, expr);
    inner_parent_name = NULL;
    constr_path = NULL;
    saved_target = arg->target->target;
    saved_indent = INDENT_LEVEL;

    PY_GEN_DEFAULT_INCLUDE();
    REDIR(OT_PY_TYPE_DECLS);
    if (arg->embed) {
        OUT("PyCompat_DEF_ANON_STRUCT(%s, %s);\n", type_name,
            constr_struct_name);
        OUT("PyCompat_DEF_TYPE(%s);\n", type_name);
        constr_path = py_get_anonymous_type_def(arg, expr, constr_member_name);
        assert(constr_path);

        if (arg->embed > 1) {
            inner_parent_name =
                py_type_name(arg, expr->parent_expr, PYTNF_CONSTR);
        }
    } else {
        PY_GEN_DEF_TYPE(type_name);
    }

    /* additionally, introduce the presence enum */
    OUT("PyCompat_DEF_ENUM(%s_PRESENT);\n", type_name);

    REDIR(OT_PY_TYPE_CONVERT);
    PY_GEN_ASNTYPE_FROMPY(type_name);
    PY_GEN_ASNTYPE_TOPY(type_name);

    REDIR(OT_PY_IMPL_CODE);
    /* make sure we capture all class fields*/
    TQ_FOR (v, &(expr->members), next) {
        if (asn1c_lang_Py_member(arg, v, expr) < 0) return -1;
    }

    /* default methods */
    if (arg->embed) {
        OUT("PY_IMPL_CHECK_CONSTRAINTS(%s, %s);\n", type_name, constr_path);
        OUT("PY_IMPL_ENCODE(%s, %s);\n", type_name, constr_path);
        OUT("PY_IMPL_DECODE(%s, %s);\n", type_name, constr_path);
        /*
         * DEALLOC is a bit special as it requires us to dereference the
         * type_DEF pointer.
         */
        OUT("PY_IMPL_DEALLOC(%s, *(%s));\n", type_name, constr_path);
        OUT("PY_IMPL_SEQ_TOPY(%s, %s);\n", type_name, constr_path);
        OUT("PY_IMPL_GENERIC_REPR(%s, %s);\n", type_name, constr_struct_name);
    } else {
        PY_GEN_TYPE_DEALLOC(type_name);
        PY_GEN_TYPE_CHECK_CONSTRAINTS(type_name);
        PY_GEN_TYPE_ENCODE(type_name);
        PY_GEN_TYPE_DECODE(type_name);
        PY_GEN_TYPE_REPR(type_name);
        OUT("PY_IMPL_SEQ_GENERIC_TOPY(%s);\n", type_name);
    }
    PY_GEN_TYPE_PARSERS(type_name);

    OUT("PyObject *PyAsnEnum%s_PRESENT_Type = NULL;\n", type_name);
    OUT("PY_IMPL_CHOICE_PRESENT_ATTR(%s);\n", type_name);

    PY_GEN_TYPE_NEW(type_name, !arg->embed);

    PY_GEN_TYPE_IS_VALID(type_name);
    /* Conversion from a generic Python object for CHOICE */
    OUT("PY_IMPL_SEQ_FROMPY(%s,\n", type_name);
    INDENT(+1);
    TQ_FOR (v, &(expr->members), next) {
        if (v->expr_type == A1TC_EXTENSIBLE) continue;
        OUT("PY_IMPL_CHOICE_INIT_ATTR(%s, %s, %s);\n", type_name, constr_struct_name, MKID_safe(v));
    }
    INDENT(-1);
    OUT(");\n");

    /* init is just calling FromPython(...) */
    if (arg->embed) {
        OUT("PY_IMPL_CHOICE_INIT_GENERIC(%s, %s);\n", type_name,
            constr_struct_name);

        if (arg->embed) {
            if (asn1c_lang_Py_type_CONSTR(arg, &ns) < 0) {
                return -1;
            }
        }
    } else {
        OUT("PY_IMPL_CHOICE_INIT(%s);\n", type_name);
    }

    /* methods for CHOICE objects will be the same */
    REDIR(OT_PY_IMPL_METHODS);
    PY_GEN_TYPE_METHODS_BEGIN(type_name);
    PY_GEN_TYPE_DEFAULT_METHODS(type_name);
    PY_GEN_TYPE_METHODS_END();

    /* members according to the ASN.1 type */
    REDIR(OT_PY_IMPL_ATTRS);
    PY_GEN_TYPE_ATTRS_BEGIN(type_name);
    OUT("{\"present\",  (getter)PyAsn%s__get_present, NULL, NULL, "
        "NULL},\n",
        type_name);
    TQ_FOR (v, &(expr->members), next) {
        if (v->expr_type == A1TC_EXTENSIBLE) continue;
        PY_GEN_TYPE_ATTRSTR(type_name, MKID_safe(v));
    }
    PY_GEN_TYPE_ATTRS_END();

    /* type spec */
    REDIR(OT_PY_IMPL_CLASS);
    PY_GEN_CLASS_BEGIN_INTERNAL(arg->pymodule_qualname, type_name,
                                py_class_name);
    if (arg->embed) {
        PY_GEN_CLASS_DOC(
            "ASN.1 anonymous type %s_TYPE part of %s", constr_struct_name,
            arg->embed > 1 ? MKID(expr->parent_expr) : parent_type_name);
    } else {
        PY_GEN_CLASS_DOC("ASN.1 %s type", py_class_name);
    }
    PY_GEN_CLASS_END();

    /* module init */
    REDIR(OT_PY_IMPL_CODE_MOD_CLEAR);
    INDENTED(OUT("Py_CLEAR(PyAsnEnum%s_PRESENT_Type);\n", type_name));

    REDIR(OT_PY_IMPL_CODE_MOD_INIT);
    INDENT(+1);
    OUT("PY_IMPL_NEW_ENUM(%s.PRESENT, PyAsnEnum%s_PRESENT_Type, -1, \n",
        py_class_name, type_name);
    INDENT(+1);
    OUT("PY_IMPL_ENUM_VALUE(PR_NOTHING, %s_PR_NOTHING, %ld);\n",
        constr_struct_name, presence_value);
    presence_value++;
    TQ_FOR (v, &(expr->members), next) {
        if (v->expr_type == A1TC_EXTENSIBLE) {
            OUT("/* Extensions may appear below */\n");
            continue;
        }

        OUT("PY_IMPL_ENUM_VALUE(PR_%s, %s, %ld);\n", MKID_safe(v),
            c_presence_name(arg, v), presence_value);
        presence_value++;
    }
    INDENT(-1);
    OUT(");\n");
    OUT("PY_IMPL_ASSIGN_ENUM_DIRECT(%s, %s_PRESENT, PRESENT);\n", type_name,
        type_name);
    INDENT(-1);

    if (arg->embed == 1) {
        INDENTED(OUT("PY_IMPL_MOD_ASSIGN_OBJECT(%s, %s_TYPE, &PyAsn%s_Type);\n",
                     parent_type_name, constr_member_name, type_name));
    } else if (arg->embed > 1) {
        INDENTED(OUT("PY_IMPL_MOD_ASSIGN_OBJECT(%s, %s_TYPE, &PyAsn%s_Type);\n",
                     inner_parent_name, constr_member_name, type_name));
    }

    PY_GEN_MOD_BASIC(type_name);
    if (!arg->embed) {
        PY_GEN_TYPE_MOD_INIT(type_name);
        PY_GEN_MODULE_ADD_TYPE(
            type_name, asn1c_make_identifier(
                           AMI_USE_PREFIX | AMI_MASK_ONLY_SPACES, expr, NULL));
    }

    if (!TYPE_IS_IMPORTED(arg, arg->expr)) {
        if (asn1c_lang_Py_stubs_generate_init(arg) < 0) return -1;
        PY_GEN_STUBS_BEGIN;
        PY_GEN_LF;
        PY_GEN_STUBS_EMBED_CONSTR(constr_member_name, expr);
        PY_GEN_STUBS_END;
    }

    ASN_XFREE(type_name);
    ASN_XFREE(constr_struct_name);
    ASN_XFREE(py_class_name);
    ASN_XFREE(parent_type_name);
    ASN_XFREE(inner_parent_name);
    ASN_XFREE(constr_member_name);
    REDIR(saved_target);
    return 0;
}

int asn1c_lang_Py_type_SIMPLE_TYPE(arg_t *arg, asn1p_expr_t *parent_expr) {
    asn1p_expr_t *expr;
    asn1p_expr_t *v;
    asn1p_ref_t *ref;

    enum asn1p_expr_type parent_expr_type;
    size_t enum_member_name_len;

    const char *tmp_name;
    char *parent_type_name;
    char *parent_struct_name;
    char *ref_type_name;
    char *el_member_name;
    char *name;
    char *constr_enum_name;
    char *constr_parent_path;

    int saved_target;
    int el_count;
    int optional;
    int indirect;
    int is_signed;
    int is_bitstr;
    int result;
    int is_open_type;

    expr = arg->expr;
    saved_target = arg->target->target;
    parent_expr_type = parent_expr ? parent_expr->expr_type : ASN_EXPR_TYPE_MAX;
    el_count = expr_elements_count(arg, expr);
    optional = TYPE_IS_OPTIONAL(expr);
    indirect = TYPE_IS_INDIRECT(expr);
    is_signed = TYPE_IS_SIGNED(arg, expr);
    is_bitstr = arg->expr->expr_type == ASN_BASIC_BIT_STRING;
    parent_type_name = NULL;
    parent_struct_name = NULL;
    ref_type_name = NULL;
    el_member_name = NULL;
    constr_enum_name = NULL;
    constr_parent_path = NULL;
    result = 0;
    ref = NULL;
    is_open_type = 0;

    if (parent_expr) {
        struct c_names parent_ns = c_expr_name(arg, parent_expr);
        parent_type_name = py_type_name(arg, parent_expr, PYTNF_NONE);
        parent_struct_name = strdup(parent_ns.base_name);
        if (arg->embed > 1) {
            constr_parent_path = py_get_anonymous_type_def(arg, parent_expr,
                                                           parent_ns.as_member);
        }
    }

    if (expr->expr_type == A1TC_REFERENCE) {
        ref = expr->reference;
        ref_type_name = strdup(MKID(expr->reference->ref_expr));
        if (ref->components[ref->comp_count - 1].name[0] == '&') {
            /* type defined elsewhere -> revert to ANY_t */
            is_open_type = 1;
        }
    }

    if (arg->embed) {
        name = strdup(asn1c_type_name(arg, arg->expr, TNF_CTYPE));
        el_member_name = strdup(MKID_safe(expr));
        REDIR(OT_PY_IMPL_CODE);

        /* sequence code is common for all types */
        if (TYPE_IS_SEQ_LIKE(parent_expr_type)) {
            if (optional) {
                OUT("PY_IMPL_SEQ_ATTR_GENERIC_FREE(%s, %s);\n",
                    parent_type_name, el_member_name);
                OUT("PY_IMPL_SEQ_ATTR_GENERIC_NEW(%s, %s, %s);\n",
                    parent_type_name, el_member_name, name);
            }
        }

        switch (expr->expr_type) {
            /* type defined elsewhere */
            case A1TC_REFERENCE: {
                // Each member gets its own custom getter and setter.
                if (is_open_type) {
                    goto embed_octet_string;
                }

                switch (parent_expr_type) {
                    case ASN_CONSTR_CHOICE:
                        PY_GEN_CHOICE_TYPEREF_GETSET(
                            parent_type_name, ref_type_name, parent_struct_name,
                            el_member_name, constr_parent_path);
                        break;
                    case ASN_CONSTR_SET:
                        PY_GEN_SET_TYPEREF_GETSET(
                            parent_type_name, parent_struct_name, ref_type_name,
                            el_member_name, optional, indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE:
                        PY_GEN_SEQ_TYPEREF_GETSET(parent_type_name,
                                                  ref_type_name, el_member_name,
                                                  optional, indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE_OF:
                    case ASN_CONSTR_SET_OF:
                        PY_GEN_SEQ_OF_TYPEREF_GETSET(parent_type_name,
                                                     ref_type_name,
                                                     constr_parent_path);
                    default:
                        break;
                };

                // we assume every referenced type is defined has a Python
                // candidate.
                PY_GEN_INCLUDE_STD(
                    OT_PY_TYPE_INCLUDES,
                    asn1c_make_identifier(AMI_USE_PREFIX | AMI_MASK_ONLY_SPACES,
                                          ref->ref_expr, NULL),
                    PY_GEN_INCLUDE_PY);
                break;
            }

            /* BASIC ASN-1 types */
            case ASN_BASIC_INTEGER:
                if (el_count && !TYPE_IS_SEQ_OF_LIKE(parent_expr_type)) {
                    goto embed_enumeration;
                }
                switch (parent_expr_type) {
                    case ASN_CONSTR_CHOICE:
                        PY_GEN_CHOICE_INTEGER_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, is_signed, constr_parent_path);
                        break;
                    case ASN_CONSTR_SET:
                        PY_GEN_SET_INTEGER_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, optional, indirect, is_signed);
                        break;
                    case ASN_CONSTR_SEQUENCE:
                        PY_GEN_SEQ_INTEGER_GETSET(parent_type_name,
                                                  el_member_name, optional,
                                                  indirect, is_signed);
                        break;
                    case ASN_CONSTR_SEQUENCE_OF:
                    case ASN_CONSTR_SET_OF:
                        PY_GEN_SEQ_OF_INTEGER_GETSET(
                            parent_type_name, is_signed, constr_parent_path);
                    default:
                        break;
                };
                break;

            case ASN_BASIC_BOOLEAN:
                switch (parent_expr_type) {
                    case ASN_CONSTR_CHOICE:
                        PY_GEN_CHOICE_BOOLEAN_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, constr_parent_path);
                        break;
                    case ASN_CONSTR_SET:
                        PY_GEN_SET_BOOLEAN_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, optional, indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE:
                        PY_GEN_SEQ_BOOLEAN_GETSET(parent_type_name,
                                                  el_member_name, optional,
                                                  indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE_OF:
                    case ASN_CONSTR_SET_OF:
                        PY_GEN_SEQ_OF_BOOLEAN_GETSET(parent_type_name,
                                                     constr_parent_path);
                    default:
                        break;
                };
                break;

            case ASN_TYPE_ANY:
            case ASN_BASIC_OCTET_STRING:
            embed_octet_string:
                // will get their own implementation
                PY_GEN_INCLUDE_STD(OT_PY_IMPL_INCLUDES, "asn_codecs_prim", 0);
                REDIR(OT_PY_IMPL_CODE);
                switch (parent_expr_type) {
                    case ASN_CONSTR_CHOICE:
                        PY_GEN_CHOICE_BYTES_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, constr_parent_path);
                        break;
                    case ASN_CONSTR_SET:
                        PY_GEN_SET_BYTES_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, optional, indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE:
                        PY_GEN_SEQ_BYTES_GETSET(parent_type_name,
                                                el_member_name, optional,
                                                indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE_OF:
                    case ASN_CONSTR_SET_OF:
                        PY_GEN_SEQ_OF_BYTES_GETSET(parent_type_name,
                                                   constr_parent_path);
                        break;
                    case A1TC_CLASSFIELD_TFS:
                        break;
                    default:
                        break;
                };
                break;

            case ASN_BASIC_REAL: {
                int is_float32 = asn1c_expr_is_float32(expr);
                switch (parent_expr_type) {
                    case ASN_CONSTR_CHOICE:
                        PY_GEN_CHOICE_REAL_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, is_float32, constr_parent_path);
                        break;
                    case ASN_CONSTR_SET:
                        PY_GEN_SET_REAL_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, optional, indirect, is_float32);
                        break;
                    case ASN_CONSTR_SEQUENCE:
                        PY_GEN_SEQ_REAL_GETSET(parent_type_name, el_member_name,
                                               optional, indirect, is_float32);
                        break;
                    case ASN_CONSTR_SEQUENCE_OF:
                    case ASN_CONSTR_SET_OF:
                        PY_GEN_SEQ_OF_REAL_GETSET(parent_type_name, is_float32,
                                                  constr_parent_path);
                    default:
                        break;
                };
                break;
            }

            case ASN_BASIC_NULL:
                switch (parent_expr_type) {
                    case ASN_CONSTR_CHOICE:
                        PY_GEN_CHOICE_NULL_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, constr_parent_path);
                        break;
                    case ASN_CONSTR_SET:
                        PY_GEN_SET_NULL_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, optional, indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE:
                        PY_GEN_SEQ_NULL_GETSET(parent_type_name, el_member_name,
                                               optional, indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE_OF:
                    case ASN_CONSTR_SET_OF:
                        PY_GEN_SEQ_OF_NULL_GETSET(parent_type_name,
                                                  constr_parent_path);
                    default:
                        break;
                };
                break;

            case ASN_BASIC_OBJECT_IDENTIFIER:
                switch (parent_expr_type) {
                    case ASN_CONSTR_CHOICE:
                        PY_GEN_CHOICE_OID_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, constr_parent_path);
                        break;
                    case ASN_CONSTR_SET:
                        PY_GEN_SET_OID_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, optional, indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE:
                        PY_GEN_SEQ_OID_GETSET(parent_type_name, el_member_name,
                                              optional, indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE_OF:
                    case ASN_CONSTR_SET_OF:
                        PY_GEN_SEQ_OF_OID_GETSET(parent_type_name,
                                                 constr_parent_path);
                    default:
                        break;
                };
                // must include new converter
                PY_GEN_INCLUDE_STD(OT_PY_TYPE_INCLUDES,
                                   "py_convert_OBJECT_IDENTIFIER",
                                   PY_GEN_INCLUDE_NONPY);
                break;

            case ASN_BASIC_BIT_STRING:
                if (el_count && !TYPE_IS_SEQ_OF_LIKE(parent_expr_type))
                    goto embed_enumeration;
                switch (parent_expr_type) {
                    case ASN_CONSTR_CHOICE:
                        PY_GEN_CHOICE_BITSTRING_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, constr_parent_path);
                        break;
                    case ASN_CONSTR_SET:
                        PY_GEN_SET_BITSTR_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, optional, indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE:
                        PY_GEN_SEQ_BITSTR_GETSET(parent_type_name,
                                                 el_member_name, optional,
                                                 indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE_OF:
                    case ASN_CONSTR_SET_OF:
                        PY_GEN_SEQ_OF_BITSTRING_GETSET(parent_type_name,
                                                       constr_parent_path);
                    default:
                        break;
                };
                break;

            case ASN_BASIC_RELATIVE_OID:
                switch (parent_expr_type) {
                    case ASN_CONSTR_CHOICE:
                        PY_GEN_CHOICE_RELATIVE_OID_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, constr_parent_path);
                        break;
                    case ASN_CONSTR_SET:
                        PY_GEN_SET_RELATIVE_OID_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, optional, indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE:
                        PY_GEN_SEQ_RELATIVE_OID_GETSET(parent_type_name,
                                                       el_member_name, optional,
                                                       indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE_OF:
                    case ASN_CONSTR_SET_OF:
                        PY_GEN_SEQ_OF_RELATIVE_OID_GETSET(parent_type_name,
                                                          constr_parent_path);
                    default:
                        break;
                };
                // must include new converter
                PY_GEN_INCLUDE_STD(OT_PY_TYPE_INCLUDES,
                                   "py_convert_RELATIVE_OID",
                                   PY_GEN_INCLUDE_NONPY);
                break;

            /*string types*/
            case ASN_BASIC_UTCTime:
            case ASN_BASIC_GeneralizedTime:
            case ASN_STRING_IA5String:
            case ASN_STRING_PrintableString:
            case ASN_STRING_VisibleString:
            case ASN_STRING_ISO646String:
            case ASN_STRING_NumericString:
            case ASN_STRING_UniversalString:
            case ASN_STRING_BMPString:
            case ASN_STRING_UTF8String:
            case ASN_STRING_GeneralString:
            case ASN_STRING_GraphicString:
            case ASN_STRING_TeletexString:
            case ASN_STRING_T61String:
            case ASN_STRING_VideotexString:
            case ASN_STRING_ObjectDescriptor:
                switch (parent_expr_type) {
                    case ASN_CONSTR_CHOICE:
                        PY_GEN_CHOICE_STRING_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, constr_parent_path);
                        break;
                    case ASN_CONSTR_SET:
                        PY_GEN_SET_STRING_GETSET(
                            parent_type_name, parent_struct_name,
                            el_member_name, optional, indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE:
                        PY_GEN_SEQ_STRING_GETSET(parent_type_name,
                                                 el_member_name, optional,
                                                 indirect);
                        break;
                    case ASN_CONSTR_SEQUENCE_OF:
                    case ASN_CONSTR_SET_OF:
                        PY_GEN_SEQ_OF_STRING_GETSET(parent_type_name,
                                                    constr_parent_path);
                    default:
                        break;
                };
                break;

            case ASN_BASIC_ENUMERATED: {
            /* ENUMERATION
             * Each enumerated type will always define a new Python class (enum)
             * that stores all defined values. In contrast to pure enumeration
             * types, the name of this type will be different. The scheme is as
             * follows:
             *
             * enum_obj_type_name :=
             *      PyAsnEnum<parent_type_name>_<member_name>Object
             *
             * enum_type_obj :=
             *      PyAsnEnum<parent_type_name>_<member_name>_Type;
             */
            embed_enumeration:
                // size is len(parent_type_id) + len(tmp_member_name) + len('_')
                // +1
                enum_member_name_len =
                    strlen(parent_type_name) + strlen(el_member_name) + 2;
                constr_enum_name = (char *)malloc(enum_member_name_len);
                snprintf(constr_enum_name, enum_member_name_len, "%s_%s",
                         parent_type_name, el_member_name);

                REDIR(OT_PY_TYPE_DECLS);
                OUT("PyCompat_DEF_ENUM(%s);\n", constr_enum_name);

                /* the type object MUST be initialized with NULL */
                REDIR(OT_PY_IMPL_CODE);
                OUT("PyObject *PyAsnEnum%s_Type = NULL;\n", constr_enum_name);

                // std enum conversion
                switch (parent_expr_type) {
                    case ASN_CONSTR_CHOICE:
                        if (is_bitstr) {
                            PY_GEN_CHOICE_NAMED_BITSTRING_GETSET(
                                parent_type_name, parent_struct_name,
                                el_member_name, constr_enum_name,
                                constr_parent_path);
                            break;
                        } else {
                            PY_GEN_CHOICE_ENUM_GETSET(
                                parent_type_name, parent_struct_name,
                                el_member_name, constr_enum_name, is_signed,
                                constr_parent_path);
                        }
                        break;
                    case ASN_CONSTR_SET:
                        if (is_bitstr) {
                            PY_GEN_SET_NAMED_BITSTR_GETSET(
                                parent_type_name, parent_struct_name,
                                el_member_name, constr_enum_name, optional,
                                indirect);
                        } else {
                            PY_GEN_SET_ENUM_GETSET(
                                parent_type_name, parent_struct_name,
                                el_member_name, constr_enum_name, is_signed,
                                optional, indirect);
                        }
                        break;
                    case ASN_CONSTR_SEQUENCE:
                        if (is_bitstr) {
                            PY_GEN_SEQ_NAMED_BITSTR_GETSET(
                                parent_type_name, el_member_name,
                                constr_enum_name, optional, indirect);
                        } else {
                            PY_GEN_SEQ_ENUM_GETSET(parent_type_name,
                                                   el_member_name,
                                                   constr_enum_name, is_signed,
                                                   optional, indirect);
                        }
                        break;
                    case ASN_CONSTR_SEQUENCE_OF:
                    case ASN_CONSTR_SET_OF: {
                        if (is_bitstr) {
                            PY_GEN_SEQ_OF_NAMED_BITSTR_GETSET(
                                parent_type_name, constr_enum_name,
                                constr_parent_path);
                        } else {
                            PY_GEN_SEQ_OF_ENUM_GETSET(
                                parent_type_name, constr_enum_name, is_signed,
                                constr_parent_path);
                        }
                        break;
                    }
                    default:
                        break;
                }

                /* module init */
                REDIR(OT_PY_IMPL_CODE_MOD_CLEAR);
                INDENTED(
                    OUT("Py_CLEAR(PyAsnEnum%s_Type);\n", constr_enum_name));

                REDIR(OT_PY_IMPL_CODE_MOD_INIT);
                INDENT(+1);
                OUT("PY_IMPL_NEW_ENUM(%s.%s_VALUES, PyAsnEnum%s_Type, -1, \n",
                    parent_type_name, el_member_name, constr_enum_name);
                INDENT(+1);
                TQ_FOR (v, &(expr->members), next) {
                    switch (v->expr_type) {
                        case A1TC_UNIVERVAL:
                            tmp_name = c_member_name(arg, v);
                            OUT("PY_IMPL_ENUM_VALUE(V_%s, %s, %s);\n",
                                c_expr_name(arg, v).as_member, tmp_name,
                                asn1p_itoa(
                                    is_bitstr ? (1 << v->value->value.v_integer)
                                              : v->value->value.v_integer));
                            break;
                        case A1TC_EXTENSIBLE:
                            OUT("/*\n");
                            OUT(" * Enumeration is extensible\n");
                            OUT(" */\n");
                            break;
                        default:
                            return -1;
                    }
                };
                INDENT(-1);
                OUT(");\n");
                OUT("PY_IMPL_ASSIGN_ENUM_DIRECT(%s, %s, %s_VALUES);\n",
                    parent_type_name, constr_enum_name, el_member_name);
                INDENT(-1);
                break;
            }

            default:
                break;
        }
    } else {
        name = strdup(MKID(expr));
        PY_GEN_DEFAULT_INCLUDE();
        /* This is a simple type alias: */
        REDIR(OT_PY_TYPE_DECLS);
        OUT("PyCompat_DEF_STRUCT(%s);\n", name);
        OUT("PyCompat_DEF_TYPE(%s);\n", name);
        if (expr->expr_type == ASN_BASIC_ENUMERATED || el_count) {
            /* Simple enumerations will be created lazily */
            OUT("PyCompat_DEF_ENUM(%s);\n", name);
        }
        /* some type converters are built-in*/
        REDIR(OT_PY_TYPE_CONVERT);
        switch (expr->expr_type) {
            case A1TC_REFERENCE: {
                ref_type_name = strdup(
                    c_expr_name(arg, expr->reference->ref_expr).base_name);
                PY_GEN_ASNTYPE_TOPY_INLINE(name);
                OUT("return PyAsn%s_ToPython(pSrc, parent);\n", ref_type_name);
                PY_GEN_END_FUNC();

                PY_GEN_ASNTYPE_FROMPY_INLINE(name);
                OUT("return PyAsn%s_FromPython(pObj, pDst);\n", ref_type_name);
                PY_GEN_END_FUNC();

                PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);
                PY_GEN_MOD_BASIC(name);

                PY_GEN_INCLUDE_STD(
                    OT_PY_TYPE_INCLUDES,
                    asn1c_make_identifier(AMI_USE_PREFIX | AMI_MASK_ONLY_SPACES,
                                          ref->ref_expr, NULL),
                    PY_GEN_INCLUDE_PY);
                break;
            }
            case ASN_BASIC_INTEGER: {
                // if this integer has named parts, convert it to an enum
                if (el_count) {
                    goto basic_enumeration;
                }

                // conversion is made easy
                PY_GEN_ASNTYPE_TOPY_INLINE(name);
                if (asn1c_type_fits_long(arg, expr) == FL_FITS_UNSIGN) {
                    OUT("return PyCompatLong_FromSize_t(*pSrc);\n");
                } else {
                    OUT("return PyCompatLong_FromSsize_t(*pSrc);\n");
                }
                PY_GEN_END_FUNC();

                PY_GEN_ASNTYPE_FROMPY_INLINE(name);
                OUT("PY_IMPL_FROMPY_COMPAT(%s, pObj, pDst);\n", name);
                OUT("PyCompatLong_Check(pObj, -1);\n");
                if (asn1c_type_fits_long(arg, expr) == FL_FITS_UNSIGN) {
                    OUT("*pDst = (%s_t)PyCompatLong_AsSize_t(pObj);\n", name);
                } else {
                    OUT("*pDst = (%s_t)PyCompatLong_AsSsize_t(pObj);\n", name);
                }
                OUT("return 0;\n");
                PY_GEN_END_FUNC();

                /*implementation*/
                PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

                /*module init*/
                PY_GEN_MOD_BASIC(name);
                break;
            }
            case ASN_BASIC_BOOLEAN: {
                // conversion is made easy
                PY_GEN_ASNTYPE_TOPY_INLINE(name);
                OUT("return PyCompatBool_FromLong(*pSrc);\n");
                PY_GEN_END_FUNC();

                PY_GEN_ASNTYPE_FROMPY_INLINE(name);
                OUT("PY_IMPL_FROMPY_COMPAT(%s, pObj, pDst);\n", name);
                OUT("*pDst = (%s_t)PyCompatBool_AsLong(pObj);\n", name);
                OUT("return 0;\n");
                PY_GEN_END_FUNC();

                /*implementation*/
                PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

                /*module init*/
                PY_GEN_MOD_BASIC(name);
                break;
            }
            case ASN_BASIC_REAL: {
                int is_float32 = asn1c_expr_is_float32(expr);
                PY_GEN_ASNTYPE_TOPY_INLINE(name);
                OUT("return PyCompatFloat_AsObject((void *)pSrc, %d);\n",
                    is_float32);
                PY_GEN_END_FUNC();

                PY_GEN_ASNTYPE_FROMPY_INLINE(name);
                OUT("PY_IMPL_FROMPY_COMPAT(%s, pObj, pDst);\n", name);
                OUT("return PyCompatFloat_FromObject(pObj, (void *)pDst, "
                    "%d);\n",
                    is_float32);
                PY_GEN_END_FUNC();

                /*implementation*/
                PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

                /*module init*/
                PY_GEN_MOD_BASIC(name);
                break;
            }
            case ASN_BASIC_NULL: {
                PY_GEN_ASNTYPE_TOPY_INLINE(name);
                OUT("return PyCompatNull_FromLong(*pSrc);\n");
                PY_GEN_END_FUNC();

                PY_GEN_ASNTYPE_FROMPY_INLINE(name);
                OUT("*pDst = (%s_t)PyCompatNull_AsLong(pObj);\n", name);
                OUT("return 0;\n");
                PY_GEN_END_FUNC();

                /*implementation*/
                PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

                /*module init*/
                PY_GEN_MOD_BASIC(name);
                break;
            }
            case ASN_BASIC_BIT_STRING: {
                PY_GEN_ASNTYPE_FROMPY_INLINE(name);
                OUT("PY_IMPL_FROMPY_COMPAT(%s, pObj, pDst);\n", name);
                if (el_count) {
                    OUT("return PyCompatFlag_FromObject(pObj, &pDst->buf, "
                        "&pDst->size);\n");
                } else {
                    OUT("return PyCompatBitArray_ToStringAndSize(pObj, "
                        "&pDst->buf, "
                        "&pDst->size);\n");
                }
                PY_GEN_END_FUNC();

                PY_GEN_ASNTYPE_TOPY_INLINE(name);
                if (el_count) {
                    OUT("return PyCompatFlag_AsObject(PyAsnEnum%s_Type, (const "
                        "char *)pSrc->buf, pSrc->size);\n",
                        name);
                } else {
                    OUT("return PyCompatBitArray_FromStringAndSize(pSrc->buf, "
                        "pSrc->size);\n");
                }
                PY_GEN_END_FUNC();

                /*implementation*/
                PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

                /*module init*/
                REDIR(OT_PY_IMPL_CODE_MOD_SETUP);
                INDENTED(PY_GEN_MOD_SETUP_SINGLE(name));

                if (el_count) {
                    REDIR(OT_PY_IMPL_CODE);
                    OUT("PyObject *PyAsnEnum%s_Type = NULL;\n", name);

                    REDIR(OT_PY_IMPL_CODE_MOD_CLEAR);
                    INDENTED(OUT("Py_CLEAR(PyAsnEnum%s_Type);\n", name));

                    REDIR(OT_PY_IMPL_CODE_MOD_INIT);
                    INDENT(+1);
                    OUT("PY_IMPL_NEW_ENUM_TYPE(PyIntFlag_Type, %s.VALUES, "
                        "PyAsnEnum%s_Type, -1, \n",
                        name, name);
                    INDENT(+1);
                    TQ_FOR (v, &(expr->members), next) {
                        switch (v->expr_type) {
                            case A1TC_UNIVERVAL:
                                tmp_name = c_member_name(arg, v);
                                OUT("PY_IMPL_ENUM_VALUE(V_%s, %s, %s);\n",
                                    c_expr_name(arg, v).as_member, tmp_name,
                                    asn1p_itoa(1 << v->value->value.v_integer));
                                break;
                            case A1TC_EXTENSIBLE:
                                OUT("/*\n");
                                OUT(" * Enumeration is extensible\n");
                                OUT(" */\n");
                                break;
                            default:
                                return -1;
                        }
                    };
                    INDENT(-1);
                    OUT(");\n");
                    OUT("PY_IMPL_ASSIGN_ENUM(%s);\n", MKID(expr));
                    INDENT(-1);
                }

                REDIR(OT_PY_IMPL_CODE_MOD_INIT);
                INDENTED(PY_GEN_MOD_INIT_SINGLE(MKID(expr)));
                break;
            }

            case ASN_BASIC_OBJECT_IDENTIFIER: { /* for now, use special
                                                   converter*/
                PY_GEN_ASNTYPE_FROMPY_INLINE(name);
                OUT("PY_IMPL_FROMPY_COMPAT(%s, pObj, pDst);\n", name);
                OUT("return PyCompatOID_FromUnicode(pObj, pDst);");
                PY_GEN_END_FUNC();

                PY_GEN_ASNTYPE_TOPY_INLINE(name);
                OUT("return PyCompatOID_AsUTF8String(pSrc);");
                PY_GEN_END_FUNC();

                /*default generic implementation*/
                PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

                /*module init*/
                PY_GEN_MOD_BASIC(name);

                // must include new converter
                PY_GEN_INCLUDE_STD(OT_PY_TYPE_INCLUDES,
                                   "py_convert_OBJECT_IDENTIFIER",
                                   PY_GEN_INCLUDE_NONPY);
                break;
            }
            case ASN_BASIC_RELATIVE_OID: { /* for now, use special converter*/
                PY_GEN_ASNTYPE_FROMPY_INLINE(name);
                OUT("PY_IMPL_FROMPY_COMPAT(%s, pObj, pDst);\n", name);
                OUT("return PyCompatRelativeOID_FromUnicode(pObj, pDst);");
                PY_GEN_END_FUNC();

                PY_GEN_ASNTYPE_TOPY_INLINE(name);
                OUT("return PyCompatRelativeOID_AsUTF8String(pSrc);");
                PY_GEN_END_FUNC();

                /*default generic implementation*/
                PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

                /*module init*/
                PY_GEN_MOD_BASIC(name);

                // must include new converter
                PY_GEN_INCLUDE_STD(OT_PY_TYPE_INCLUDES,
                                   "py_convert_RELATIVE_OID",
                                   PY_GEN_INCLUDE_NONPY);
                break;
            }

            /*Bytes types*/
            case ASN_TYPE_ANY:
            case ASN_BASIC_OCTET_STRING: {
                PY_GEN_ASNTYPE_FROMPY_INLINE(name);
                OUT("PY_IMPL_FROMPY_COMPAT(%s, pObj, pDst);\n", name);
                OUT("return PyCompatBytes_ToStringAndSize(pObj, &pDst->buf, "
                    "&pDst->size);");
                PY_GEN_END_FUNC();

                PY_GEN_ASNTYPE_TOPY_INLINE(name);
                OUT("return PyCompatBytes_FromStringAndSize(pSrc->buf, "
                    "pSrc->size);");
                PY_GEN_END_FUNC();

                /*implementation*/
                PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

                /*module init*/
                PY_GEN_MOD_BASIC(name);
                break;
            }

            /*string types*/
            case ASN_BASIC_UTCTime:
            case ASN_BASIC_GeneralizedTime:
            case ASN_STRING_IA5String:
            case ASN_STRING_PrintableString:
            case ASN_STRING_VisibleString:
            case ASN_STRING_ISO646String:
            case ASN_STRING_NumericString:
            case ASN_STRING_UniversalString:
            case ASN_STRING_BMPString:
            case ASN_STRING_UTF8String:
            case ASN_STRING_GeneralString:
            case ASN_STRING_GraphicString:
            case ASN_STRING_TeletexString:
            case ASN_STRING_T61String:
            case ASN_STRING_VideotexString:
            case ASN_STRING_ObjectDescriptor: {
                PY_GEN_ASNTYPE_FROMPY_INLINE(name);
                OUT("PY_IMPL_FROMPY_COMPAT(%s, pObj, pDst);\n", name);
                OUT("pDst->buf = (uint8_t "
                    "*)PyCompatUnicode_AsUTF8AndSize(pObj, "
                    "&pDst->size);\n");
                OUT("return pDst->buf ? 0 : -1;\n");
                PY_GEN_END_FUNC();

                PY_GEN_ASNTYPE_TOPY_INLINE(name);
                OUT("return PyCompatUnicode_FromStringAndSize(pSrc->buf, "
                    "pSrc->size);\n");
                PY_GEN_END_FUNC();

                /*implementation*/
                PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);

                /*module init*/
                PY_GEN_MOD_BASIC(name);
                break;
            }

            case ASN_BASIC_ENUMERATED: {
            basic_enumeration:
                PY_GEN_ASNTYPE_FROMPY_INLINE(name);
                OUT("PY_IMPL_FROMPY_COMPAT(%s, pObj, pDst);\n", name);
                OUT("return PyCompatEnum_FromObject(pObj, (void *)pDst, %d);\n",
                    is_signed);
                PY_GEN_END_FUNC();

                PY_GEN_ASNTYPE_TOPY_INLINE(name);
                if (asn1c_type_fits_long(arg, expr) == FL_FITS_UNSIGN) {
                    OUT("return "
                        "PyCompatEnum_FromSize_t(PyAsnEnum%s_Type,*pSrc);\n",
                        name);
                } else {
                    OUT("return PyCompatEnum_FromSsize_t(PyAsnEnum%s_Type, "
                        "*pSrc);\n",
                        name);
                }
                PY_GEN_END_FUNC();

                /*implementation for base type*/
                PY_GEN_BASIC_CLASS(arg->pymodule_qualname, name);
                REDIR(OT_PY_IMPL_CODE);
                OUT("PyObject *PyAsnEnum%s_Type = NULL;\n", name);

                /*implementation for enum type*/
                REDIR(OT_PY_IMPL_CODE_MOD_SETUP);
                INDENT(+1);
                PY_GEN_MOD_SETUP_SINGLE(name);  // single type here

                /* clear out the referenced enum type*/
                REDIR(OT_PY_IMPL_CODE_MOD_CLEAR);
                OUT("Py_CLEAR(PyAsnEnum%s_Type);\n", name);
                INDENT(-1);

                /*module init*/
                REDIR(OT_PY_IMPL_CODE_MOD_INIT);
                INDENT(+1);
                OUT("PY_IMPL_NEW_ENUM(%s.VALUES, PyAsnEnum%s_Type, -1, \n",
                    name, name);
                INDENT(+1);
                TQ_FOR (v, &(expr->members), next) {
                    switch (v->expr_type) {
                        case A1TC_UNIVERVAL:
                            tmp_name = c_member_name(arg, v);
                            OUT("PY_IMPL_ENUM_VALUE(V_%s, %s, %s);\n",
                                c_expr_name(arg, v).as_member, tmp_name,
                                asn1p_itoa(v->value->value.v_integer));
                            break;
                        case A1TC_EXTENSIBLE:
                            OUT("/*\n");
                            OUT(" * Enumeration is extensible\n");
                            OUT(" */\n");
                            break;
                        default:
                            return -1;
                    }
                };
                INDENT(-1);
                OUT(");\n");

                OUT("PY_IMPL_ASSIGN_ENUM(%s);\n", name);
                PY_GEN_MOD_ADD_OBJECT(name);
                INDENT(-1);

                break;
            }

            default: {
                printf("Unknown type %d\n", expr->expr_type);
                PY_GEN_ASNTYPE_FROMPY(name);
                PY_GEN_ASNTYPE_TOPY(name);
                break;
            }
        }
        PY_GEN_TYPE_MOD_INIT(name);
        PY_GEN_MODULE_ADD_TYPE(
            name, asn1c_make_identifier(AMI_USE_PREFIX | AMI_MASK_ONLY_SPACES,
                                        expr, NULL));
    }

    result = asn1c_lang_Py_stubs_SIMPLE_TYPE(arg, parent_expr);

    REDIR(saved_target);
    ASN_XFREE(parent_type_name);
    ASN_XFREE(parent_struct_name);
    ASN_XFREE(ref_type_name);
    ASN_XFREE(el_member_name);
    ASN_XFREE(name);
    ASN_XFREE(constr_enum_name);
    return result;
}

int asn1c_lang_Py_type_SEQ_OF(arg_t *arg) {
    struct c_names ns;
    asn1p_expr_t *expr;
    asn1p_expr_t *memb;
    asn1p_expr_t *v;

    char *list_type_name;
    char *list_struct_name;
    char *py_class_qualname;
    char *parent_type_name;
    char *list_constr_path;
    char *inner_parent_name;
    char *inner_parent_struct_name;
    char *list_member_name;

    int saved_target;
    int saved_indent;
    int el_count;
    enum asn1p_expr_marker_e flags;

    expr = arg->expr;
    memb = TQ_FIRST(&expr->members);
    ns = c_name(arg);
    saved_target = arg->target->target;
    list_type_name = py_type_name(arg, expr, PYTNF_CONSTR);
    list_struct_name = strdup(ns.base_name);
    list_member_name = strdup(ns.as_member);
    py_class_qualname = py_type_name(arg, expr, PYTNF_CLASS);
    parent_type_name = NULL;
    list_constr_path = NULL;
    inner_parent_name = NULL;
    inner_parent_struct_name = NULL;
    saved_indent = INDENT_LEVEL;
    el_count = expr_elements_count(arg, memb);

    if (expr->parent_expr != NULL) {
        arg->embed--;
        parent_type_name = py_type_name(arg, expr->parent_expr, PYTNF_CONSTR);
        list_constr_path =
            py_get_anonymous_type_def(arg, expr, list_member_name);
        arg->embed++;
    }

    PY_GEN_DEFAULT_INCLUDE();
    if (memb->Identifier == NULL) {
        memb->Identifier = strdup("Member");
    }
    flags = memb->marker.flags;
    memb->marker.flags &= ~EM_INDIRECT;
    asn1c_lang_Py_member(arg, memb, expr);
    memb->marker.flags = flags;
    ns = c_name(arg);

    REDIR(OT_PY_TYPE_DECLS);
    if (arg->embed && !expr->_anonymous_type) {
        OUT("typedef struct %s %s_t;\n", ns.base_name, list_type_name);
    }
    PY_GEN_DEF_TYPE(list_type_name);

    /* type converters */
    REDIR(OT_PY_TYPE_CONVERT);
    PY_GEN_ASNTYPE_FROMPY(list_type_name);
    PY_GEN_ASNTYPE_TOPY(list_type_name);

    REDIR(OT_PY_IMPL_CODE);
    OUT("PY_IMPL_SEQ_OF_NEW(%s);\n", list_type_name);
    OUT("PY_IMPL_SEQ_OF_DEALLOC(%s, asn_set_empty);\n", list_type_name);
    OUT("PY_IMPL_SEQ_OF_INIT(%s);\n", list_type_name);
    OUT("PY_IMPL_SEQ_OF_REPR(%s);\n", list_type_name);
    /*type converters impl*/
    if (arg->embed) {
        OUT("PY_IMPL_CHECK_CONSTRAINTS(%s, %s);\n", list_type_name,
            list_constr_path);
        OUT("PY_IMPL_ENCODE(%s, %s);\n", list_type_name, list_constr_path);
        OUT("PY_IMPL_DECODE(%s, %s);\n", list_type_name, list_constr_path);
        OUT("PY_IMPL_SEQ_TOPY(%s, %s);\n", list_type_name, list_constr_path);

        if (arg->embed > 1) {
            inner_parent_name =
                py_type_name(arg, expr->parent_expr, PYTNF_CONSTR);
            inner_parent_struct_name =
                strdup(c_expr_name(arg, expr->parent_expr).base_name);
        }
    } else {
        PY_GEN_TYPE_CHECK_CONSTRAINTS(list_type_name);
        PY_GEN_TYPE_ENCODE(list_type_name);
        PY_GEN_TYPE_DECODE(list_type_name);

        OUT("PY_IMPL_SEQ_GENERIC_TOPY(%s);\n", list_type_name);
    }
    PY_GEN_TYPE_PARSERS(list_type_name);
    PY_GEN_TYPE_IS_VALID(list_type_name);

    if (arg->embed) {
        /* embed into constructed types */
        if (asn1c_lang_Py_type_CONSTR(arg, &ns) < 0) {
            return -1;
        }
    }

    /* PySequence protocol */
    OUT("PY_IMPL_SEQ_OF_LEN(%s);\n", list_type_name);
    OUT("PY_IMPL_SEQ_OF_GETITEM(%s);\n", list_type_name);
    /* These ones will be populated in SIMPLE_TYPE, CHOICE or SEQUENCE */
    // OUT("PY_IMPL_SEQ_OF_SETITEM(%s, %s);\n", list_type_name,
    // memb_struct_name); OUT("PY_IMPL_SEQ_OF_ADD(%s, %s);\n", list_type_name,
    // memb_struct_name);
    OUT("PY_IMPL_SEQ_OF_CLEAR(%s);\n", list_type_name);
    OUT("PY_IMPL_SEQ_OF_EXTEND(%s);\n", list_type_name);

    REDIR(OT_PY_IMPL_METHODS);
    PY_GEN_TYPE_METHODS_BEGIN(list_type_name);
    PY_GEN_TYPE_DEFAULT_METHODS(list_type_name);
    OUT("PY_IMPL_METHODDEF_ITEM(%s, clear, METH_NOARGS),\n", list_type_name);
    OUT("PY_IMPL_METHODDEF_ITEM(%s, extend, METH_VARARGS),\n", list_type_name);
    OUT("PY_IMPL_METHODDEF_ITEM(%s, add, METH_VARARGS | METH_KEYWORDS),\n",
        list_type_name);
    PY_GEN_TYPE_METHODS_END();

    REDIR(OT_PY_IMPL_ATTRS);
    PY_GEN_TYPE_ATTRS_BEGIN(list_type_name);
    PY_GEN_TYPE_ATTRS_END();

    OUT("static PySequenceMethods PyAsn%s_seq_methods = {\n", list_type_name);
    INDENT(+1);
    OUT(".sq_item = (ssizeargfunc)PyAsn%s__getitem,\n", list_type_name);
    OUT(".sq_length = (lenfunc)PyAsn%s__len,\n", list_type_name);
    OUT(".sq_ass_item = (ssizeobjargproc)PyAsn%s__setitem,\n", list_type_name);
    INDENT(-1);
    OUT("};\n");

    REDIR(OT_PY_IMPL_CLASS);
    PY_GEN_CLASS_BEGIN_INTERNAL(arg->pymodule_qualname, list_type_name,
                                py_class_qualname);
    if (arg->embed) {
        PY_GEN_CLASS_DOC("ASN.1 anonymous sequence %s_TYPE part of %s",
                         list_member_name, parent_type_name);
    } else {
        PY_GEN_CLASS_DOC("ASN.1 %s type", ns.as_member);
    }
    OUT(".tp_as_sequence = &PyAsn%s_seq_methods\n", list_type_name);
    PY_GEN_CLASS_END();

    REDIR(OT_PY_IMPL_CODE_MOD_INIT);
    if (arg->embed) {
        INDENTED(OUT("PY_IMPL_MOD_ASSIGN_OBJECT(%s, %s_TYPE, &PyAsn%s_Type);\n",
                     parent_type_name, list_member_name, list_type_name));
        // } else if(arg->embed > 1) {
        //     INDENTED(OUT("PY_IMPL_MOD_ASSIGN_OBJECT(%s, %s_TYPE,
        //     &PyAsn%s_Type);\n",
        //                  inner_parent_name, ns.as_member, list_type_name));
    } else {
        INDENTED(PY_GEN_MOD_INIT_SINGLE(list_type_name));
    }

    REDIR(OT_PY_IMPL_CODE_MOD_SETUP);
    INDENTED(PY_GEN_MOD_SETUP_SINGLE(list_type_name));
    if (!arg->embed) {
        PY_GEN_TYPE_MOD_INIT(list_type_name);
        PY_GEN_MODULE_ADD_TYPE(
            list_type_name,
            asn1c_make_identifier(AMI_USE_PREFIX | AMI_MASK_ONLY_SPACES, expr,
                                  NULL));
    }

    if (!TYPE_IS_IMPORTED(arg, arg->expr)) {
        PY_GEN_STUBS_BEGIN;
        INDENT_LEVEL = arg->embed;
        INDENT(+1);
        OUT("def clear(self) -> None: ...\n");
        OUT("def __len__(self) -> int: ...\n");
        OUT("def __delitem__(self, index: int) -> None: ...\n");
        INDENT(-1);
        PY_GEN_LF;
        PY_GEN_STUBS_EMBED_CONSTR(list_member_name, expr);
        PY_GEN_STUBS_END;
    }

    INDENT_LEVEL = saved_indent;
    REDIR(saved_target);
    ASN_XFREE(list_type_name);
    ASN_XFREE(list_struct_name);
    ASN_XFREE(py_class_qualname);
    ASN_XFREE(list_constr_path);
    ASN_XFREE(inner_parent_name);
    ASN_XFREE(list_member_name);
    ASN_XFREE(inner_parent_struct_name);
    return 0;
}

static int asn1c_lang_Py_member(arg_t *arg, asn1p_expr_t *memb,
                                asn1p_expr_t *parent_expr) {
    arg->expr = memb;
    arg->embed++;
    switch (memb->expr_type) {
        case A1TC_EXTENSIBLE:
        case ASN_CONSTR_SEQUENCE:
        case ASN_CONSTR_CHOICE:
        case ASN_CONSTR_SET:
        case ASN_CONSTR_SEQUENCE_OF:
        case ASN_CONSTR_SET_OF:
        case ASN_CONSTR_OPEN_TYPE:
            break;

        /* All other cases are handled */
        default: {
            if (asn1c_lang_Py_type_SIMPLE_TYPE(arg, parent_expr) < 0) {
                return -1;
            }
        }
    }

    arg->embed--;
    arg->expr = parent_expr;
    return 0;
}

/* stubs gen */
int asn1c_lang_Py_stubs_SIMPLE_TYPE(arg_t *arg, asn1p_expr_t *parent_expr) {
    asn1p_expr_t *expr;
    asn1p_expr_t *v;
    asn1p_expr_t *ref_expr;

    asn1p_ref_t *ref;

    const char *py_conv_type;
    char *memb_name;

    int saved_target;
    int is_bitstr;
    int el_count;
    int indent_level;
    int parent_is_seq;
    int optional;

    expr = arg->expr;
    saved_target = arg->target->target;
    is_bitstr = expr->expr_type == ASN_BASIC_BIT_STRING;
    el_count = expr_elements_count(arg, expr);
    memb_name = NULL;
    ref = NULL;
    ref_expr = NULL;
    indent_level = INDENT_LEVEL;
    py_conv_type = PY_TYPE_MAP[expr->expr_type];
    memb_name = strdup(MKID(expr));
    parent_is_seq =
        parent_expr ? TYPE_IS_SEQ_OF_LIKE(parent_expr->expr_type) : 0;
    optional = (expr->marker.flags & EM_OPTIONAL) ||
               (TYPE_IS_UNION(expr->parent_expr));

    if (expr->expr_type == A1TC_REFERENCE) {
        py_conv_type = c_expr_name(arg, expr->reference->ref_expr).as_member;
        ref = expr->reference;
        ref_expr = asn1c_get_REFERENCE(arg, expr);
        if (ref_expr) {
            py_conv_type = PY_TYPE_MAP[ASN_TYPE_ANY];
        } else {
            /* add an import statement and skip stubs */
            if (TYPE_IS_IMPORTED(arg, expr->reference->ref_expr)) {
                PY_OUTER(
                    OT_PY_STUBS_IMPORTS,
                    OUT("from asn1_external_mod import %s\n", py_conv_type););
                return 0;
            }
        }
    }

    if (arg->embed && TYPE_IS_IMPORTED(arg, arg->expr->parent_expr) ||
        TYPE_IS_IMPORTED(arg, expr)) {
        return 0;
    }

    PY_GEN_STUBS_BEGIN;
    INDENT_LEVEL = arg->embed;

    if (!el_count || expr->expr_type == A1TC_REFERENCE) {
        if (!py_conv_type) {
            WARNING("SIMPLE TYPE %#x - no python type found!", expr->expr_type);
            py_conv_type = "EXT_Any";
        }

        if (arg->embed) {
            if (!parent_is_seq) {
                OUT("%s: %s%s\n", memb_name, py_conv_type,
                    (optional) ? " | None" : "");
            } else {
                PY_GEN_STUBS_SEQ_OF(py_conv_type, "");
            }
        } else {
            OUT("class %s(_Asn1BasicType[%s%s]):\n", memb_name, py_conv_type,
                (optional) ? " | None" : "");
            INDENTED(OUT("pass\n"));
            PY_GEN_LF;
        }
    } else {
        switch (expr->expr_type) {
            case ASN_BASIC_INTEGER:
            case ASN_BASIC_BIT_STRING:
            case ASN_BASIC_ENUMERATED: {
                if (!arg->embed) {
                    OUT("class %s(_Asn1Type):\n", memb_name);
                    INDENT(+1);
                } else {
                    PY_GEN_LF;
                }
                OUT("class %s%sVALUES(EXT_%s):\n", arg->embed ? memb_name : "",
                    arg->embed ? "_" : "", is_bitstr ? "IntFlag" : "IntEnum");
                INDENT(+1);
                TQ_FOR (v, &(expr->members), next) {
                    switch (v->expr_type) {
                        case A1TC_UNIVERVAL:
                            OUT("V_%s = %s%s\n", c_expr_name(arg, v).as_member,
                                is_bitstr ? "1 << " : "",
                                asn1p_itoa(v->value->value.v_integer));
                            break;
                        case A1TC_EXTENSIBLE:
                            OUT("/*\n");
                            OUT(" * Enumeration is extensible\n");
                            OUT(" */\n");
                            break;
                        default:
                            return -1;
                    }
                };
                INDENT(-1);
                PY_GEN_LF;
                if (arg->embed) {
                    if (!parent_is_seq) {
                        OUT("%s: %s_VALUES%s\n", memb_name, memb_name,
                            (optional) ? " | None" : "");
                    } else {
                        PY_GEN_STUBS_SEQ_OF(memb_name, "_VALUES");
                    }
                    INDENT(-1);
                } else {
                    PY_GEN_STUBS_ENUM_PROPERTY(memb_name, optional);
                    OUT("def __init__(self, value: VALUES = ...) -> None: "
                        "...\n");
                    PY_GEN_LF;
                }
                break;
            }
            default:
                break;
        }
    }

    PY_GEN_STUBS_END;

    INDENT_LEVEL = indent_level;
    REDIR(saved_target);
    ASN_XFREE(memb_name);
    if (ref_expr) asn1p_expr_free(ref_expr);
    return 0;
}

int asn1c_lang_Py_stubs_SEQUENCE(arg_t *arg) {
    struct c_names cn;

    char *type_name;

    int saved_target;
    int saved_indent;
    int is_set;

    saved_target = arg->target->target;
    cn = c_name(arg);
    type_name = strdup(cn.as_member);
    saved_indent = INDENT_LEVEL;
    is_set = TYPE_IS_SET(arg->expr);

    if (TYPE_IS_IMPORTED(arg, arg->expr)) {
        PY_OUTER(OT_PY_STUBS_IMPORTS,
                 OUT("from asn1_external_mod import %s\n", type_name););
        return 0;
    }

    PY_GEN_STUBS_BEGIN;
    INDENT_LEVEL = arg->embed;
    if (arg->embed) {
        PY_GEN_LF;
        OUT("class %s_TYPE(_Asn1Type): # %s\n", type_name,
            is_set ? "SET" : "SEQUENCE");
    } else {
        OUT("class %s(_Asn1Type): # %s\n", type_name, is_set ? "SET" : "SEQUENCE");
    }
    PY_GEN_STUBS_END;

    INDENT_LEVEL = saved_indent;
    REDIR(saved_target);
    ASN_FREE(type_name);
    return 0;
}

int asn1c_lang_Py_stubs_CHOICE(arg_t *arg) {
    struct c_names cn;

    asn1p_expr_t *expr;
    asn1p_expr_t *v;

    char *type_name;

    int saved_target;
    int saved_indent;
    size_t presence_value;

    expr = arg->expr;
    saved_target = arg->target->target;
    cn = c_name(arg);
    type_name = strdup(cn.as_member);
    saved_indent = INDENT_LEVEL;
    presence_value = 0;

    if (TYPE_IS_IMPORTED(arg, arg->expr)) {
        PY_OUTER(OT_PY_STUBS_IMPORTS,
                 OUT("from asn1_external_mod import %s\n", type_name););
        return 0;
    }

    PY_GEN_STUBS_BEGIN;
    INDENT_LEVEL = arg->embed;
    if (arg->embed) {
        PY_GEN_LF;
        OUT("class %s_TYPE(_Asn1Type): # CHOICE\n", type_name);
    } else {
        OUT("class %s(_Asn1Type): # CHOICE\n", type_name);
    }
    INDENT(+1);
    OUT("class PRESENT(EXT_IntEnum):\n");
    INDENT(+1);
    OUT("PR_NOTHING = 0\n");
    presence_value++;
    TQ_FOR (v, &(expr->members), next) {
        if (v->expr_type == A1TC_EXTENSIBLE) {
            OUT("/* Extensions may appear below */\n");
            continue;
        }

        OUT("PR_%s = %ld\n", MKID_safe(v), presence_value);
        presence_value++;
    }
    INDENT(-1);
    PY_GEN_LF;
    OUT("@property\n");
    OUT("def present(self) -> PRESENT: ...\n");
    INDENT(-1);

    PY_GEN_STUBS_END;

    INDENT_LEVEL = saved_indent;
    REDIR(saved_target);
    ASN_FREE(type_name);
    return 0;
}

int asn1c_lang_Py_stubs_SEQ_OF(arg_t *arg) {
    struct c_names cn;

    char *type_name;

    int saved_indent;
    int saved_target;

    cn = c_name(arg);
    saved_indent = INDENT_LEVEL;
    saved_target = arg->target->target;
    type_name = strdup(cn.as_member);

    if (TYPE_IS_IMPORTED(arg, arg->expr)) {
        PY_OUTER(OT_PY_STUBS_IMPORTS,
                 OUT("from asn1_external_mod import %s\n", type_name););
        return 0;
    }

    PY_GEN_STUBS_BEGIN;
    INDENT_LEVEL = arg->embed;
    if (arg->embed) {
        PY_GEN_LF;
        OUT("class %s_TYPE(_Asn1Type):\n", type_name);
    } else {
        OUT("class %s(_Asn1Type):\n", type_name);
    }
    PY_GEN_STUBS_END;

    INDENT_LEVEL = saved_indent;
    REDIR(saved_target);
    ASN_FREE(type_name);
    return 0;
}

/* static functions */
static inline int asn1c_expr_is_float32(asn1p_expr_t *expr) {
    asn1cnst_range_t *range = asn1constraint_compute_OER_range(
        expr->Identifier, ASN_BASIC_REAL, expr->combined_constraints,
        ACT_EL_RANGE, 0, 0, 0);
    int is_float32 = range->narrowing == NARROW_FLOAT32;
    asn1constraint_range_free(range);
    return is_float32;
}

static char *py_type_name(arg_t *arg, asn1p_expr_t *expr, int flags) {
    /* NAMING SCHEME:
     * The basic naming scheme should be following the parent's type name:
     *
     * <type_name> := [ <parent_type_name> '_' ] <type_name> [ '_' <anon_name>]
     * <anon_name> := '_ANON_' <anon_number>
     */
    char *constr_type_name = NULL, *tmp_name = strdup(MKID(expr)),
         *tmp_parent_name = NULL;
    size_t tmp_len = 0;
    asn1p_expr_t *parent = expr->parent_expr;

    while (parent && arg->embed) {
        if (!parent->parent_expr) {
            // got root type
            tmp_parent_name = strdup(MKID(parent));
            break;
        }
        parent = parent->parent_expr;
    }

    if (tmp_parent_name) {
        tmp_len = strlen(tmp_parent_name) + strlen(tmp_name) + 2;
        constr_type_name = malloc(tmp_len);
        snprintf(constr_type_name, tmp_len, "%s%c%s", tmp_parent_name,
                 (flags & PYTNF_CLASS) ? '.' : '_', tmp_name);
    } else {
        constr_type_name = strdup(tmp_name);
    }

    ASN_CLEAR(tmp_name);
    if ((arg->embed == 1 && (flags & PYTNF_CONSTR)) || arg->embed > 1) {
        // anonymous type
        tmp_name = constr_type_name;
        tmp_len = strlen(constr_type_name) + 7 + 20;
        constr_type_name = malloc(tmp_len);
        snprintf(constr_type_name, tmp_len, "%s_ANON_%d", tmp_name,
                 expr->_type_unique_index);
    }
    ASN_XFREE(tmp_parent_name);
    ASN_XFREE(tmp_name);
    return constr_type_name;
}

static char *get_py_class_name(arg_t *arg, asn1p_expr_t *expr) {
    asn1p_expr_t *parent = expr->parent_expr;
    char *constr_type_name = NULL, *tmp_name = NULL, *tmp_parent_name = NULL;
    size_t tmp_len = 0, cur_len = 0;
    int has_parent = 0;

    constr_type_name = strdup(MKID(expr));
    cur_len = strlen(constr_type_name);

    while (parent && arg->embed) {
        has_parent = parent->parent_expr ? 1 : 0;
        tmp_parent_name = strdup(MKID(parent));
        tmp_name = constr_type_name;
        tmp_len = strlen(tmp_parent_name) + cur_len + 1 + (has_parent ? 5 : 0);
        constr_type_name = malloc(tmp_len + 1);

        snprintf(constr_type_name, tmp_len + 1, "%s%s.%s", tmp_parent_name,
                 has_parent ? "_TYPE" : "", tmp_name);
        ASN_XFREE(tmp_name);
        ASN_XFREE(tmp_parent_name);
        parent = parent->parent_expr;
        cur_len = tmp_len;
        constr_type_name[tmp_len] = '\0';
    }

    if (arg->embed) {
        tmp_len = cur_len + 5;
        tmp_name = constr_type_name;
        constr_type_name = malloc(tmp_len + 1);
        snprintf(constr_type_name, tmp_len + 1, "%s_TYPE", tmp_name);
        ASN_FREE(tmp_name);
        constr_type_name[tmp_len] = '\0';
    }

    return constr_type_name;
}

static char *py_parent_type_name(arg_t *arg, asn1p_expr_t *expr) {
    char *tmp_name = NULL;
    asn1p_expr_t *parent = expr->parent_expr;
    while (parent && arg->embed) {
        if (!parent->parent_expr) {
            // got root type
            tmp_name = strdup(MKID(parent));
            break;
        }
        parent = parent->parent_expr;
    }
    return tmp_name;
}

static size_t asn1c_get_member_index(arg_t *arg, asn1p_expr_t *expr,
                                     const char *name) {
    size_t index = 0;
    asn1p_expr_t *v = NULL;
    TQ_FOR (v, &(expr->members), next) {
        /* first, test for raw identifier , then test for safe identifier */
        if (strcmp(name, v->Identifier) == 0) return index;
        if (strcmp(name, MKID_safe(v)) == 0) return index;
        ++index;
    }
    return index;
}

static char *py_get_anonymous_type_def(arg_t *arg, asn1p_expr_t *expr,
                                       const char *name) {
    /* Find a path to the anonymous type definition */
    asn1p_expr_t *parent = NULL;
    char *tmp_name = NULL, *constr_path = NULL;
    size_t index = 0, tmp_len = 0, cur_len = 0, cur_alloc = 0;

    parent = expr->parent_expr;
    if (!parent) {
        return NULL;
    }

    /* fetch the parent index */
    index = asn1c_get_member_index(arg, parent, name);
    if (parent->parent_expr == NULL) {
        /* only one layer:
         * <path> := 'asn_DEF' <parent_name> '.elements[' <index> '].type'
         */
        tmp_name = strdup(MKID(parent));
        tmp_len = strlen(tmp_name) + 24 + ASN1C_MAX_INT_WIDTH;
        constr_path = malloc(tmp_len);
        snprintf(constr_path, tmp_len, "asn_DEF_%s.elements[%ld].type",
                 tmp_name, index);
        ASN_FREE(tmp_name);
    } else {
        constr_path = malloc(256);
        cur_len = 0;
        cur_alloc = 256;
        memset(constr_path, 0, 256);

        while (parent->parent_expr != NULL) {
            /* <path> := '->elements[' <index> '].type */
            tmp_len = cur_len + 24 + ASN1C_MAX_INT_WIDTH;
            if (tmp_len > cur_alloc) {
                constr_path = realloc(constr_path, tmp_len);
                memset(constr_path + cur_len, 0, tmp_len - cur_len);
                cur_alloc = tmp_len;
            }
            tmp_name = strdup(constr_path);
            snprintf(constr_path, tmp_len, "->elements[%ld].type%s", index,
                     cur_len ? tmp_name : "");
            cur_len = tmp_len;
            ASN_FREE(tmp_name);

            tmp_name = strdup(MKID(parent));
            parent = parent->parent_expr;
            index = asn1c_get_member_index(arg, parent, tmp_name);
            ASN_FREE(tmp_name);
        }

        tmp_len = cur_len + 24 + ASN1C_MAX_INT_WIDTH;
        if (tmp_len > cur_alloc) {
            constr_path = realloc(constr_path, tmp_len);
            memset(constr_path + cur_len, 0, tmp_len - cur_len);
            cur_alloc = tmp_len;
        }
        tmp_name = strndup(constr_path, cur_len);
        snprintf(constr_path, tmp_len, "asn_DEF_%s.elements[%ld].type%s",
                 MKID(parent), index, tmp_name);
        ASN_FREE(tmp_name);
    }
    return constr_path;
}

static int expr_elements_count(arg_t *arg, asn1p_expr_t *expr) {
    asn1p_expr_t *topmost_parent;
    asn1p_expr_t *v;
    int elements = 0;

    topmost_parent = WITH_MODULE_NAMESPACE(
        expr->module, expr_ns,
        asn1f_find_terminal_type_ex(arg->asn, expr_ns, expr));
    if (!topmost_parent) return 0;

    if (!(topmost_parent->expr_type & ASN_CONSTR_MASK) &&
        !(topmost_parent->expr_type == ASN_BASIC_INTEGER) &&
        !(topmost_parent->expr_type == ASN_BASIC_ENUMERATED) &&
        !(topmost_parent->expr_type == ASN_BASIC_BIT_STRING))
        return 0;

    TQ_FOR (v, &(topmost_parent->members), next) {
        if (v->expr_type != A1TC_EXTENSIBLE) elements++;
    }

    return elements;
}

static int asn1c_lang_Py_type_CONSTR(arg_t *arg, struct c_names *pre_cn) {
    struct c_names cn;
    asn1p_expr_t *expr;

    char *constr_type_name;
    char *constr_struct_name;
    char *constr_member_name;
    char *constr_path;
    char *parent_type_name;
    char *inner_parent_type_name;
    char *inner_parent_struct_name;
    char *inner_parent_path;

    int saved_target;
    int deep_embed;
    int indirect;
    int optional;

    expr = arg->expr;
    cn = (pre_cn != NULL) ? *pre_cn : c_name(arg);
    constr_type_name = py_type_name(arg, expr, PYTNF_CONSTR);
    constr_struct_name = strdup(cn.base_name);
    constr_member_name = strdup(MKID(expr));

    constr_path = NULL;
    parent_type_name = py_parent_type_name(arg, expr);
    inner_parent_type_name = NULL;
    inner_parent_struct_name = NULL;
    inner_parent_path = NULL;
    saved_target = arg->target->target;
    deep_embed = arg->embed > 1;
    optional = TYPE_IS_OPTIONAL(expr);
    indirect = TYPE_IS_INDIRECT(expr) || optional;

    REDIR(OT_PY_IMPL_CODE);
    if (arg->embed) {
        constr_path = py_get_anonymous_type_def(arg, expr, constr_member_name);
        if (deep_embed) {
            struct c_names inner_cn = c_expr_name(arg, expr->parent_expr);
            inner_parent_type_name =
                py_type_name(arg, expr->parent_expr, PYTNF_CONSTR);
            inner_parent_struct_name = strdup(inner_cn.base_name);
            inner_parent_path = py_get_anonymous_type_def(
                arg, expr->parent_expr, inner_cn.as_member);
        }

        switch (expr->parent_expr->expr_type) {
            case ASN_CONSTR_SEQUENCE: {
                OUT("PY_IMPL_SEQ_ANON_ATTR_FROMPY(%s, %s, %s%s%s, %s);\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    constr_member_name, (indirect ? "" : "&"), "src->",
                    constr_member_name, constr_type_name);
                OUT("PY_IMPL_SEQ_ANON_ATTR_TOPY(%s, %s, %s%s%s, %s);\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    constr_member_name, (indirect ? "" : "&"), "src->",
                    constr_member_name, constr_type_name);
                OUT("PY_IMPL_SEQ_INNER%s_SETATTR(%s, %s, %s, %s);\n",
                    optional ? "_OPT" : "",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    constr_member_name, constr_member_name, constr_type_name);
                OUT("PY_IMPL_SEQ_INNER_GETATTR(%s, %s, %sself->ob_value->%s, "
                    "%s);\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    constr_member_name, (indirect ? "" : "&"),
                    constr_member_name, constr_type_name);
                break;
            }
            case ASN_CONSTR_CHOICE: {
                OUT("PY_IMPL_SEQ_ANON_ATTR_FROMPY(%s, %s, %s%s%s, %s);\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    constr_member_name, (indirect ? "" : "&"), "src->choice.",
                    constr_member_name, constr_type_name);
                OUT("PY_IMPL_SEQ_ANON_ATTR_TOPY(%s, %s, %s%s%s, %s);\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    constr_member_name, (indirect ? "" : "&"), "src->choice.",
                    constr_member_name, constr_type_name);
                OUT("PY_IMPL_CHOICE_GENERIC_SETATTR(%s, %s, %s, *%s);\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    deep_embed ? inner_parent_struct_name : parent_type_name,
                    constr_member_name, constr_path);
                OUT("PY_IMPL_CHOICE_GETATTR(%s, %s, %s);\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    deep_embed ? inner_parent_struct_name : parent_type_name,
                    constr_member_name);
                break;
            }
            case ASN_CONSTR_SET: {
                OUT("PY_IMPL_SEQ_ANON_ATTR_FROMPY(%s, %s, %s%s%s, %s);\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    constr_member_name, (indirect ? "" : "&"), "src->",
                    constr_member_name, constr_type_name);
                OUT("PY_IMPL_SEQ_ANON_ATTR_TOPY(%s, %s, %s%s%s, %s);\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    constr_member_name, (indirect ? "" : "&"), "src->",
                    constr_member_name, constr_type_name);
                OUT("PY_IMPL_SET_INNER%s_SETATTR(%s, %s, %s, %s, %s%s%s);\n",
                    optional ? "_OPT" : "",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    deep_embed ? inner_parent_struct_name : parent_type_name,
                    constr_member_name, constr_member_name, constr_type_name,
                    (indirect ? ", *" : ""), (indirect) ? constr_path : "");
                OUT("PY_IMPL_SET_INNER_GETATTR(%s, %s, %s, "
                    "%sself->ob_value->%s, "
                    "%s);\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    deep_embed ? inner_parent_struct_name : parent_type_name,
                    constr_member_name, (indirect ? "" : "&"),
                    constr_member_name, constr_type_name);
                break;
            }
            case ASN_CONSTR_SEQUENCE_OF:
            case ASN_CONSTR_SET_OF: {
                OUT("PY_IMPL_SEQ_OF_ITEM_TOPY(%s, %s_t, PyAsn%s_ToPython(src, "
                    "parent));\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    constr_type_name, constr_type_name);
                OUT("PY_IMPL_SEQ_OF_ITEM_FROMPY(%s, %s_t, "
                    "PyAsn%s_FromPython(value, target));\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    constr_type_name, constr_type_name);
                OUT("PY_IMPL_SEQ_OF_FROMPY(%s, %s_t);\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    constr_type_name);
                if (inner_parent_path != NULL) {
                    OUT("PY_IMPL_SEQ_OF_GENERIC_SETITEM(%s, %s_t, "
                        "*PY_IMPL_SEQ_OF_COMPONENT_TYPE(%s));\n",
                        deep_embed ? inner_parent_type_name : parent_type_name,
                        constr_type_name, inner_parent_path);
                } else {
                    OUT("PY_IMPL_SEQ_OF_SETITEM(%s, %s_t);\n",
                        deep_embed ? inner_parent_type_name : parent_type_name,
                        constr_type_name);
                }
                OUT("PY_IMPL_SEQ_OF_ADD(%s, %s_t);\n",
                    deep_embed ? inner_parent_type_name : parent_type_name,
                    constr_type_name);
                break;
            }
            default:
                break;
        }
    }
    REDIR(saved_target);

    ASN_FREE(constr_type_name);
    ASN_FREE(constr_struct_name);
    ASN_FREE(constr_member_name);
    ASN_XFREE(constr_path);
    ASN_FREE(parent_type_name);
    ASN_XFREE(inner_parent_type_name);
    ASN_XFREE(inner_parent_struct_name);
    ASN_XFREE(inner_parent_path);
    return 0;
}

static int asn1c_lang_Py_stubs_generate_init(arg_t *arg) {
    asn1p_expr_t *expr;
    asn1p_expr_t *v;
    asn1p_expr_t *ref_expr;

    const char *type_name;
    char *memb_name;

    int saved_target;
    int saved_indent;

    saved_target = arg->target->target;
    saved_indent = INDENT_LEVEL;
    expr = arg->expr;

    PY_GEN_STUBS_BEGIN;
    INDENT_LEVEL = arg->embed;
    INDENT(+1);
    OUT("def __init__(\n");
    INDENT(+1);
    OUT("self, /, *,\n");
    TQ_FOR (v, &(expr->members), next) {
        struct c_names cn = c_expr_name(arg, v);
        int el_count = expr_elements_count(arg, v);
        if (v->expr_type == A1TC_EXTENSIBLE) {
            continue;
        }

        memb_name = strdup(cn.as_member);
        /* We have get the target type name  based on the expression type */
        switch (v->expr_type) {
            case ASN_CONSTR_SEQUENCE_OF:
            case ASN_CONSTR_SET_OF:
            case ASN_CONSTR_SEQUENCE:
            case ASN_CONSTR_CHOICE: {
                OUT("%s: %s_TYPE = ...,\n", memb_name, memb_name);
                break;
            }
            case A1TC_REFERENCE: {
                ref_expr = asn1c_get_REFERENCE(arg, v);
                if (ref_expr) {
                    type_name = PY_TYPE_MAP[ASN_TYPE_ANY];
                } else {
                    type_name =
                        c_expr_name(arg, v->reference->ref_expr).as_member;
                }
                OUT("%s: %s = ...,\n", memb_name, type_name);
                break;
            }

            default: {
                if (el_count) {
                    OUT("%s: %s_VALUES = ...,\n", memb_name, memb_name);
                } else {
                    type_name = PY_TYPE_MAP[v->expr_type];
                    if (type_name != NULL) {
                        OUT("%s: %s = ...,\n", memb_name, type_name);
                    } else {
                        OUT("%s: EXT_Any = ...,\n", memb_name);
                    }
                }
                break;
            }
        }
        ASN_XFREE(memb_name);
    }
    INDENT(-1);
    OUT(") -> None: ...\n");

    PY_GEN_STUBS_END;

    INDENT_LEVEL = saved_indent;
    REDIR(saved_target);
    return 0;
}

static asn1p_expr_t *asn1c_get_REFERENCE(arg_t *arg,
                                         asn1p_expr_t *target_expr) {
    asn1p_expr_t *expr;
    asn1p_expr_t *ref_expr;
    asn1p_ref_t *ref;

    expr = target_expr ? target_expr : arg->expr;
    ref_expr = NULL;
    if (expr->expr_type != A1TC_REFERENCE || expr->reference == NULL) {
        return NULL;
    }

    ref = expr->reference;
    if (ref->components[ref->comp_count - 1].name[0] == '&') {
        ref_expr = WITH_MODULE_NAMESPACE(
            expr->module, expr_ns,
            asn1f_class_access_ex(arg->asn, expr->module, expr_ns, expr,
                                  expr->rhs_pspecs, ref));
        if (ref_expr == NULL) return NULL;

        ref_expr = asn1p_expr_clone(ref_expr, 0);
        if (ref_expr) {
            free(ref_expr->Identifier);
            ref_expr->Identifier = strdup(expr->Identifier);
            if (ref_expr->Identifier == NULL) {
                asn1p_expr_free(ref_expr);
                return NULL;
            }
        }
    }

    return ref_expr;
}