import enum
from typing import override

# GENERATION NOT IMPLEMENTED
class NamedSigned8:
    class VALUES(enum.Enum):
        NamedSigned8_first = -1
        NamedSigned8_second = 0
        NamedSigned8_third = 1

    def __init__(self, value: VALUES | int = ...) -> None: ...
    @override
    def __repr__(self) -> str: ...
    def encode(self) -> bytes: ...
    @staticmethod
    def decode(data: bytes) -> NamedSigned8: ...
    def is_valid(self) -> bool: ...
    def check_constraints(self) -> None: ...
    @property
    def value(self) -> VALUES: ...
    @value.setter
    def value(self, value: VALUES | int) -> None: ...
