ExampleModule DEFINITIONS ::= BEGIN

-- basic types

Signed8 ::= INTEGER (-127..127)

NamedSigned8 ::= INTEGER {
    first(-1),
    second(0),
    third(1)
}

ExampleBoolean ::= BOOLEAN
ExampleBitString ::= BIT STRING
ExampleOctetString ::= OCTET STRING (SIZE(1..32))
ExampleNull ::= NULL
ExampleObjectIdentifier ::= OBJECT IDENTIFIER

END