ExampleModule DEFINITIONS AUTOMATIC TAGS  ::= BEGIN

-- basic types

Signed8 ::= INTEGER (-127..127)

NamedSigned8 ::= INTEGER {
    first(-1),
    second(0),
    third(1)
}

ExampleNamedBitString ::= BIT STRING {
    zero(0),
    one(1),
    two(2)
}

ExampleBoolean ::= BOOLEAN
ExampleBitString ::= BIT STRING
ExampleOctetString ::= OCTET STRING (SIZE(1..32))
ExampleNull ::= NULL
ExampleObjectIdentifier ::= OBJECT IDENTIFIER
ExampleRelativeOid ::= RELATIVE-OID
ExampleReal ::= REAL
ExampleUTF8String ::= UTF8String

ExampleChoice ::= CHOICE {
    foo         OCTET STRING,
    bar         INTEGER,
    baz         NamedSigned8,
    cReal       REAL,
    cBitString  BIT STRING,
    cBoolean    BOOLEAN,
    cNull       NULL,
    cOid        OBJECT IDENTIFIER,
    cRelOid     RELATIVE-OID,
    cEnum       ENUMERATED {
        ceA(1),
        ceB(2),
        ceC(3)
    },
    cNamedInt  INTEGER {
        cniA(1),
        cniB(2),
        cniC(3)
    },
    cNamedBitString  BIT STRING {
        cnbsA(1),
        cnbsB(2),
        cnbsC(3),
        cnbsOutOfBounds(1000)
    },
    cSeq        SEQUENCE {
        ciInt       INTEGER
    },
    cChoice     CHOICE {
        ciReal      REAL,
        ciBool      BOOLEAN,
        ciSeq       SEQUENCE {
            cis        INTEGER
        }
    }
}

ExampleSequence ::= SEQUENCE {
    sInt            INTEGER,
    sIntOpt         INTEGER OPTIONAL,
    sanInt          INTEGER {
        inamedA(1),
        inamedB(2),
        inamedC(3)
    },
    snInt           NamedSigned8,
    snIntOpt        NamedSigned8 OPTIONAL,
    sBoolOpt        BOOLEAN OPTIONAL,
    sBool           BOOLEAN,
    sBitStr         BIT STRING,
    snBitStr        BIT STRING {
        namedA(0),
        namedB(1),
        namedC(2)
    },
    sBitStrOpt      BIT STRING OPTIONAL,
    sOctetStr       OCTET STRING,
    sOctetStrOpt    OCTET STRING OPTIONAL,
    sNull           NULL,
    sNullOpt        NULL OPTIONAL,
    sOid            OBJECT IDENTIFIER,
    sOidOpt         OBJECT IDENTIFIER OPTIONAL,
    sRelOid         RELATIVE-OID,
    sRelOidOpt      RELATIVE-OID OPTIONAL,
    sReal           REAL,
    sRealOpt        REAL OPTIONAL,
    sSeq            SEQUENCE {
        siInt           INTEGER,
        siSeq           SEQUENCE {
            siiInt          INTEGER
        }
    },
    sChoice         CHOICE {
        sicInt          INTEGER
    }
}

END