[build-system]
requires = ["hatchling", "scikit-build-core~=0.9.0", "asn1cpython-support==0.0.1"]
build-backend = "hatchling.build"

[project]
name = "example-mod"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "bitarray",
]

[tool.hatch.version]
path = "src/example_mod/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/example_mod tests}"

[tool.coverage.run]
source_pkgs = ["example_mod", "tests"]
branch = true
parallel = true
omit = [
  "src/example_mod/__about__.py",
]

[tool.coverage.paths]
example_mod = ["src/example_mod", "*/example-mod/src/example_mod"]
tests = ["tests", "*/example-mod/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.hatch.build.targets.wheel.hooks.scikit-build]
experimental = true

[tool.hatch.build.targets.sdist]
include = ["*.pyi"]

[tool.hatch.build.targets.wheel]
artifacts = ["*.pyi"]

# To set a custom compiler and skeletons path, use custom defines
# [tool.scikit-build.cmake.define]
# A1C_PATH = "..."
# A1C_SKELETONS_PATH = "..."